<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <label>Open Enrollment</label>
    <navType>Standard</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Open_Enrollment_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>SFDC_Volunteer_Event__c</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>National Open Enrollment</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Open_Enrollment_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>SFDC_Volunteer_Event__c</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Facilitator_Contact</recordType>
        <type>Flexipage</type>
        <profile>National Open Enrollment</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Facilitator_Contact</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Open_Enrollment_Record_Page11</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>SFDC_Volunteer_Event__c</pageOrSobjectType>
        <recordType>SFDC_Volunteer_Event__c.OE_Kit</recordType>
        <type>Flexipage</type>
        <profile>API User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Open_Enrollment_Record_Page11</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>SFDC_Volunteer_Event__c</pageOrSobjectType>
        <recordType>SFDC_Volunteer_Event__c.OE_Kit</recordType>
        <type>Flexipage</type>
        <profile>Local Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Open_Enrollment_Record_Page11</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>SFDC_Volunteer_Event__c</pageOrSobjectType>
        <recordType>SFDC_Volunteer_Event__c.OE_Kit</recordType>
        <type>Flexipage</type>
        <profile>Local Sales Dual</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Open_Enrollment_Record_Page11</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>SFDC_Volunteer_Event__c</pageOrSobjectType>
        <recordType>SFDC_Volunteer_Event__c.OE_Kit</recordType>
        <type>Flexipage</type>
        <profile>National Open Enrollment</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Open_Enrollment_Record_Page11</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>SFDC_Volunteer_Event__c</pageOrSobjectType>
        <recordType>SFDC_Volunteer_Event__c.OE_Kit</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Open_Enrollment_Meetings_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Open_Enrollment_Meetings__c</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>National Open Enrollment</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Open_Enrollment_Meetings_Record_Page1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Open_Enrollment_Meetings__c</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>Home_Page_Default1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Local Implementations</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>Home_Page_Default1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Local Implementations Dual</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>Home_Page_Default1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Local Sales</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>Home_Page_Default1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Local Sales Dual</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>Tab</actionName>
        <content>Home_Page_Default1</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>SME</profile>
    </profileActionOverrides>
    <tabs>standard-home</tabs>
    <tabs>standard-Feed</tabs>
    <tabs>standard-Account</tabs>
    <tabs>SFDC_Volunteer_Event__c</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-report</tabs>
    <tabs>Open_Enrollment_Meetings__c</tabs>
    <tabs>SFDC_Volunteer_Participant__c</tabs>
    <tabs>Support_Request__c</tabs>
    <tabs>Underwriting_Record__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>Open_Enrollment_UtilityBar</utilityBar>
</CustomApplication>
