public Class A0123
{
public Account createAccount(String name)  //method to create account
{
//Test comment for Account A01234
//Test1
Account a1 = new Account();
a1 .Name = name;
return a1 ;
//sai007hcxvnnv ccvbvcbcbvnxvcvbxbcnvcnvbncbvcnmnvbnvmbmcmbncmvnbmcvbnnmbnvcnvbcvbjcbvbjc bvc bcjbcjvbjcmv bc nv nc vnc vncvcvbmcm cm mvcbcmmc m cbvncnbvncmbmcvbmmcvmbmcvmbmcmvbmmcbmmvbmvmbmcvmbmcvmbmcvmvbcm bmcm vmv mvc mb mcv bmcv mb cmv mvc mbc vmbc vm bmc vnbc nbc vbcnv bfcvmc  vcn vnc n bmc vm vcm  vc bn bmc m n n  ggggggggggggggggggggggggggggggggggggggggggggggggggggggggukjhbjhbhjvhvhvhvhv
}
}
