public with sharing class AccountTriggerHandler
{
    public void onBeforeInsert( )
    {
    }
    
    public void onBeforeUpdate( )
    {
  
    }
    
     /*public void onBeforeDelete( List<Account> oldAccountIn)
    {
   
    }*/
    
    public void onAfterInsert( )
    {
    }
    
      
    /*public void onAfterDelete(list<Account> oldAccountIn )
    {
       
    }
    
    public void onAfterUndelete(list<Account> newAccountIn )
    {
    }*/
    
    public void onAfterUpdate( )
    {
       
    }
    
    
}