public class BusinessClass {
    public BusinessClass(){
        
    }
    
    Public void add(Integer a ,integer b){
        Integer c;//test method multiply   tt
        c = a+b;
    }
    //test method multiply   tt
    Public void sub(Integer a ,integer b){
        Integer c;
        //test method multiply   tt
        c = a-b;
    }
    //test method multiply   tt
    Public void multiply(Integer a ,integer b){
        Integer c;
        c = a*b;
    }

}