/***
Static Variable Test Class
Usage : Test Replace hardcoded values
***/

@isTest
public class staticVariableClass_Test {
    
    @isTest
    public static void testStaticVariables(){
        String  StageNameInitiated  =staticVariableClass.StageNameInitiated;
        String  RenewalLocal    =staticVariableClass.RenewalLocal;
        String  RenewalLocal1   =staticVariableClass.RenewalLocal1;
        String  IGAPSold    =staticVariableClass.IGAPSold;
        String  Renewed =staticVariableClass.Renewed;
        String  Notrenewingincurrentperiod  =staticVariableClass.Notrenewingincurrentperiod;
        String  NewBusinessLocal    =staticVariableClass.NewBusinessLocal;
        String  Sold    =staticVariableClass.Sold;
        String  IGAPLocal   =staticVariableClass.IGAPLocal;
        String  IGCLocal    =staticVariableClass.IGCLocal;
        String  SoldRenewed =staticVariableClass.SoldRenewed;
        String  InProgress  =staticVariableClass.InProgress;
        String  RecordsProcessed    =staticVariableClass.RecordsProcessed;
        String  NumberOfErrors  =staticVariableClass.NumberOfErrors;
        String  String_cronexpression   =staticVariableClass.String_cronexpression;
        String  SIC =staticVariableClass.SIC;
        String  AccountName =staticVariableClass.AccountName;
        String  Entity  =staticVariableClass.Entity;
        String  Region  =staticVariableClass.Region;
        String  UniCare =staticVariableClass.UniCare;
        String  size    =staticVariableClass.size;
        Decimal emp =staticVariableClass.emp;
        String  AK  =staticVariableClass.AK;
        String  California  =staticVariableClass.California;
        String CreateGrpWARNINGFLAG = staticVariableClass.CreateGrpWARNINGFLAG;
        String Georgia = staticVariableClass.Georgia;
        String  Indiana =staticVariableClass.Indiana;
        String  ClosedWon   =staticVariableClass.ClosedWon;
        String  TeamMemberRole  =staticVariableClass.TeamMemberRole;
        String  DNCError    =staticVariableClass.DNCError;
        String  DNCTstAcc   =staticVariableClass.DNCTstAcc;
        String  DNCTstAccState  =staticVariableClass.DNCTstAccState;
        String  DNCTstEntity    =staticVariableClass.DNCTstEntity;
        String  DNCTstAcc2  =staticVariableClass.DNCTstAcc2;
        String  DNCStrBefore    =staticVariableClass.DNCStrBefore;
        String  DNCStrTitle =staticVariableClass.DNCStrTitle;
        String  DNCStrPath  =staticVariableClass.DNCStrPath;
        String  DNCStrShareType =staticVariableClass.DNCStrShareType;
        String  DNCStatusPen    =staticVariableClass.DNCStatusPen;
        String  DNCStatusNew    =staticVariableClass.DNCStatusNew;
        String  DNCStatusApproved   =staticVariableClass.DNCStatusApproved;
        String  DNCStrGrpPref   =staticVariableClass.DNCStrGrpPref;
        String  DNCStrGrp   =staticVariableClass.DNCStrGrp;
        String  DNCStrAccManager    =staticVariableClass.DNCStrAccManager;
        String  DNCStrEmpPref   =staticVariableClass.DNCStrEmpPref;
        String DeleteQliGETQLIPlans = staticVariableClass.DeleteQliGETQLIPlans;         
        String  String_CarveCron_Exp1   =staticVariableClass.String_CarveCron_Exp1;
        String  String_CarveCron_Exp2   =staticVariableClass.String_CarveCron_Exp2;
        String  LgQliUpdateProdStage    =staticVariableClass.LgQliUpdateProdStage;
        String  LgQliUpdateProdProbability  =staticVariableClass.LgQliUpdateProdProbability;
        String  testAccBillingStreet    =staticVariableClass.testAccBillingStreet;
        String  testAccBillingPostalCode    =staticVariableClass.testAccBillingPostalCode;
        String  testAccBillingCity  =staticVariableClass.testAccBillingCity;
        String  testAccBillingCountry   =staticVariableClass.testAccBillingCountry;
        String  testAccBillingState =staticVariableClass.testAccBillingState;
        String  testProdName    =staticVariableClass.testProdName;
        String  testProdTermYearsLeft   =staticVariableClass.testProdTermYearsLeft;
        String  CreateGrpGETGROUPNUMBER =staticVariableClass.CreateGrpGETGROUPNUMBER;
        String  CreateGrpUPDATENEXTNUMBERUTILITY    =staticVariableClass.CreateGrpUPDATENEXTNUMBERUTILITY;
        String  CreateGrpSTATUSCODE =staticVariableClass.CreateGrpSTATUSCODE;
        String  CreateGrpSUCCESS    =staticVariableClass.CreateGrpSUCCESS;
        String  CreateGrpFAILURE    =staticVariableClass.CreateGrpFAILURE;
        String  CreateGrpERRMSG =staticVariableClass.CreateGrpERRMSG;
        String  CreateGrpREQUESTGROUPNUMBERSTEP =staticVariableClass.CreateGrpREQUESTGROUPNUMBERSTEP;
        String  CreateGrpACCTID =staticVariableClass.CreateGrpACCTID;
        String  CreateGrpGROUPNUMBER    =staticVariableClass.CreateGrpGROUPNUMBER;
        String  CreateGrpERROR  =staticVariableClass.CreateGrpERROR;
        String  CreateGrpLASTNUMBEREMPTY    =staticVariableClass.CreateGrpLASTNUMBEREMPTY;
        String  CreateGrpNOSTATERECORD  =staticVariableClass.CreateGrpNOSTATERECORD;
        String  CreateGrpGROUPNUMBERALREADYINUSE    =staticVariableClass.CreateGrpGROUPNUMBERALREADYINUSE;
        String  CreateGrpQUOTEID    =staticVariableClass.CreateGrpQUOTEID;
        String  CreateGrpCLAIMSYSTEM    =staticVariableClass.CreateGrpCLAIMSYSTEM;
        String  CreateGrpLOB    =staticVariableClass.CreateGrpLOB;
        String  DeleteQliGETQLI =staticVariableClass.DeleteQliGETQLI;
        String  DeleteQliSPLITRECORDSELECTION   =staticVariableClass.DeleteQliSPLITRECORDSELECTION;
        String  DeleteQliQLIPRODLIST    =staticVariableClass.DeleteQliQLIPRODLIST;
        String  DeleteQliQLIID  =staticVariableClass.DeleteQliQLIID;
        String CreateGroupNumberGAReset  = staticVariableClass.CreateGroupNumberGAReset ;
        Integer CreateGroupNumberDigits = staticVariableClass.CreateGroupNumberDigits;
        
        string  TBD =staticVariableClass.TBD;
        string  GroupNum    =staticVariableClass.GroupNum;
        string  AnthemHealthGuide   =staticVariableClass.AnthemHealthGuide;
        string  NumericFive =staticVariableClass.NumericFive;
        string  OpportunityName =staticVariableClass.OpportunityName;
        string  OpportunityStageName    =staticVariableClass.OpportunityStageName;
        string  userLastName    =staticVariableClass.userLastName;
        string  userFirstName   =staticVariableClass.userFirstName;
        string  userAlias   =staticVariableClass.userAlias;
        string  userEmail   =staticVariableClass.userEmail;
        string  userUsername    =staticVariableClass.userUsername;
        string  userTimeZoneSidKey  =staticVariableClass.userTimeZoneSidKey;
        string  userLanguageLocaleKey   =staticVariableClass.userLanguageLocaleKey;
        string  userEmailEncodingKey    =staticVariableClass.userEmailEncodingKey;
        string  userLocaleSidKey    =staticVariableClass.userLocaleSidKey;
        
        string  LocalNASCOandWGS =  staticVariableClass.LocalNASCOandWGS;
        string  WorkInProgress  =  staticVariableClass.WorkInProgress  ;
        string  PendingSmeReview  =  staticVariableClass.PendingSmeReview;
        string  LocalImplementations  =  staticVariableClass.LocalImplementations;
        string  LGChangeRequestOffCycle  =  staticVariableClass.LGChangeRequestOffCycle;
        string  ChangeRequestOffCycle  =  staticVariableClass.ChangeRequestOffCycle;
        string  UpsellNo  =  staticVariableClass.UpsellNo;
        string  UpsellYes  =  staticVariableClass.UpsellYes;
        string  Termone  =  staticVariableClass.Termone;
        string  Dental  =  staticVariableClass.Dental;
        string  Vision  =  staticVariableClass.Vision;
        string  Life  =  staticVariableClass.Life;
        string  Disability  =  staticVariableClass.Disability  ;
        Decimal  QuantityOrPrice  =  staticVariableClass.QuantityOrPrice;
        string  JAANASCOandWGS  =  staticVariableClass.JAANASCOandWGS;
        string  AIMTesting03  =  staticVariableClass.AIMTesting03;
        string  AIMTesting02  =  staticVariableClass.AIMTesting02;
        string  AIMTesting01  =  staticVariableClass.AIMTesting01;
        string  Order  =  staticVariableClass.Order;
        string  Account  =  staticVariableClass.Account;
        string  Opportunity  =  staticVariableClass.Opportunity  ;
        string  NewBusiness  =  staticVariableClass.NewBusiness  ;
        string  LocalNewBusiness  =  staticVariableClass.LocalNewBusiness;
        string  ReadyforImps  =  staticVariableClass.ReadyforImps;
        string  LGProspect  =  staticVariableClass.LGProspect;
        string  AnthemDentalProdName  =  staticVariableClass.AnthemDentalProdName;
        string  AnthemLifeProdName  =  staticVariableClass.AnthemLifeProdName;
        string  Draft  =  staticVariableClass.Draft;
        string  NewBusinessLocalhyphen  =  staticVariableClass.NewBusinessLocalhyphen;
        string Medical = staticVariableClass.Medical;
        string Renew = staticVariableClass.Renew;
        string SubscribersRollup = staticVariableClass.SubscribersRollup;
        string MembersRollup = staticVariableClass.MembersRollup;
        string TotalMedicalSubscribers = staticVariableClass.TotalMedicalSubscribers;
        string TotalMedicalMembers = staticVariableClass.TotalMedicalMembers;
        string  idCardStage  =   staticVariableClass.defaultIDCardStage;
        string  Product  =   staticVariableClass.Product;
        string  Plan  =   staticVariableClass.Plan;
        string  OppType  =   staticVariableClass.OppType;
        string  ProductStage  =   staticVariableClass.ProductStage;
        string  RecordType  =   staticVariableClass.RecordType;
        string  Reason  =   staticVariableClass.Reason;
        string  slash  =   staticVariableClass.slash;
        string  CreateGroupNumberNH  =   staticVariableClass.CreateGroupNumberNH;
        string  CreateGroupNumberNH1  =   staticVariableClass.CreateGroupNumberNH1;
        string  assertEquals = staticVariableClass.assertEquals;
        string  assertNotEquals = staticVariableClass.assertNotEquals;
        string Maine = staticVariableClass.Maine;
        string Connecticut = staticVariableClass.Connecticut;
        string SYSTEM_ADMIN = staticVariableClass.SYSTEM_ADMIN;
        string QUOTE_ID = staticVariableClass.QUOTE_ID;
        string stage04Approved = staticVariableClass.STAGE04_APPROVED;
        string local = staticVariableClass.LOCAL;
        string commercialSalesString = staticVariableClass.COMMERCIAL_SALES_STRING;
        string lgSmeRecordCreationString = staticVariableClass.LG_SME_RECORD_CREATION_STRING;
        string afterUpdateString = staticVariableClass.AFTER_UPDATE_STRING;
        string userIdFormat = staticVariableClass.USER_ID_FORMAT;
        string newGroupsAndUpsellsQueue = staticVariableClass.NEW_GROUPS_AND_UPSELLS_QUEUE;
        string queue = staticVariableClass.QUEUE;
        string disabilityFound = staticVariableClass.DISABILITY_FOUND;
        string lifeFound = staticVariableClass.LIFE_FOUND;
        string dentalFound = staticVariableClass.DENTAL_FOUND;
        string visionFound = staticVariableClass.VISION_FOUND;
        string ltdProdType = staticVariableClass.LTD_PROD_TYPE;
        string stdProdType = staticVariableClass.STD_PROD_TYPE;
        string termed = staticVariableClass.TERMED;
        string renewal = staticVariableClass.RENEWAL;
        string fullGroupTerm = staticVariableClass.FULL_GROUP_TERM;
        string preWork = staticVariableClass.PRE_WORK;
        string classLgQuoteLineItem= staticVariableClass.CLASS_LG_QUOTE_LINE_ITEM;
        string createHwPkgMethod = staticVariableClass.CREATE_HW_PACKAGE_PROGRAMS;
        string createHwPkgFuture= staticVariableClass.CREATE_HWPACKAGE_PROGRAMS_FUTURE;
        string error= staticVariableClass.ERROR ;
        string hpccProductName = staticVariableClass.HPCCCODE_PRODUCT_NAME ;
        string hpcccode= staticVariableClass.HPCCCODE ;
        string fundingType= staticVariableClass.FUNDING_TYPE;
        string state= staticVariableClass.STATE;
        string incentiveTypeNA = staticVariableClass.INCENTIVE_TYPE_NA;
        string incentiveTypeGC = staticVariableClass.INCENTIVE_TYPE_GC;
        string incentiveTypeAD = staticVariableClass.INCENTIVE_TYPE_AD;
        string relationType = staticVariableClass.RELATIONSHIP_TYPE;
        string childNumber = staticVariableClass.CHILD_NUMBER;
        string grpsize050= staticVariableClass.GROUP_SIZE_0_50;
        string grpsize5199= staticVariableClass.GROUP_SIZE_51_99;
        string grpsize100249= staticVariableClass.GROUP_SIZE_100_249;
        string grpsize250499= staticVariableClass.GROUP_SIZE_250_499;
        string grpsize500999= staticVariableClass.GROUP_SIZE_500_999;
        string grpsize1000= staticVariableClass.GROUP_SIZE_1000;
        string qliTriggerName = staticVariableClass.QLI_TRIGGERNAM_AFTERINSERT;
        string upsell               = staticVariableClass.UPSELL;
        string aHGName              = staticVariableClass.AHG_PRODUCT_NAME;
        string aHGrecordType        =staticVariableClass.AHG_RECORDTYPE;
        string qliAfterInsertTrigger =staticVariableClass.QLI_AFTER_INSERT_TRIGGER;
        String  clasAssociatePkgToPlan= staticVariableClass.CLASS_LG_ASSOCIATE_PACKAGE_TO_PLAN;
        String  associateNewPkg     =   staticVariableClass.ASSOCIATE_NEW_PKG;
        String  associateExistingPkg=   staticVariableClass.ASSOCIATE_EXISTING_PKG;
        String  parentProd          =   staticVariableClass.PARENT_PRODUCT;
        String  selectedParentProd  =   staticVariableClass.SELECTED_PARENT_PRODUCT;
        String  childBundle         =   staticVariableClass.CHILD_BUNDLES;
        String  childList           =   staticVariableClass.CHILD_LIST;
        String  currentPlan         =   staticVariableClass.CURRENT_PLAN;
        String  incentiveType       =   staticVariableClass.INCENTIVE_TYPE;
        String  incentiveTypeSelect =   staticVariableClass.INCENTIVE_TYPE_SELECT;
        String  trueString          =   staticVariableClass.TRUE_STRING;
        String  planList            =   staticVariableClass.PLAN_LIST;
        String  productSelection    =   staticVariableClass.PRODUCT_SELECTION;
        String  commercialSelection =   staticVariableClass.COMMERCIAL_SELECTIONS;
        String  commercialFlow      =   staticVariableClass.COMMERCIAL_FLOW;
        String  commercialClinical  =   staticVariableClass.COMMERCIAL_CLINICAL;
        String  parentProdId        =   staticVariableClass.PARENT_PRODUCT_ID;
        String  commercialClinicalNode   =  staticVariableClass.COMMERCIAL_CLINICAL_NODE;
        String  finalPgmList        =   staticVariableClass.FINAL_PROGRAM_LIST;
        String  commercialBuyUp     =   staticVariableClass.COMMERCIAL_BUY_UPS;
        String  commercialBuyUpSelection     =  staticVariableClass.COMMERCIAL_BUYUP_SELECTION;
        String  program             =   staticVariableClass.PROGRAM;
        String  prodCategory        =   staticVariableClass.PRODUCT_CATEGORY;
        String  localRenewal        =   staticVariableClass.LOCAL_RENEWAL;
        //HW Indicator
        String  completed           =   staticVariableClass.COMPLETED;
        string  failed              =   staticVariableClass.FAILED;
        string  wgsClaimSystem      =   staticVariableClass.WGS_CLAIM_SYSTEM;
        String  viewString          =   staticVariableClass.VIEW_STRING;
        
       //PRDCRM : 50723
        String pooled        =  staticVariableClass.POOLED;
        String standard        =  staticVariableClass.STANDARD;
        
        //PRDCRM-50634 - GLD - 201.2
        String sModify        =  staticVariableClass.MODIFY;
        String sStateRegulator     =  staticVariableClass.STATE_REGULATOR;
        String sHcrStatus      =  staticVariableClass.HCR_STATUS;
        
        //PRDCRM-51890 - Send parameters to P2A on Create CEP Case Button from QLI
        String sCalendar        =  staticVariableClass.CALENDAR;
        String sBenefit    =  staticVariableClass.BENEFIT;
        String sCEPCase        =  staticVariableClass.CEP_CASE;
        String sAso        =  staticVariableClass.ASO;
        String sFi        =  staticVariableClass.FI;
        String sNa        =  staticVariableClass.N_A;
        String sAsoFi        =  staticVariableClass.ASO_FI;
        
        //GLD - PRDCRM:50840 - Auto create L&D SME for Supplemental Health Products
        String sHospIndemnity  =  staticVariableClass.HOSPITAL_INDEMNITY;
        String sAccident        =  staticVariableClass.ACCIDENT;
        String sCriticalIll        =  staticVariableClass.CRITICAL_ILLNESS;
        
        //GLD - PRDCRM - 52626 : Plan Update Screen and Quote Plan Card Update
        String sVisionPlan = staticVariableClass.VISION_PLANS;
        
        System.assertEquals(staticVariableClass.CLASS_LG_QUOTE_LINE_ITEM, classLgQuoteLineItem,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CREATE_HW_PACKAGE_PROGRAMS, createHwPkgMethod,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CREATE_HWPACKAGE_PROGRAMS_FUTURE, createHwPkgFuture,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.FULL_GROUP_TERM, fullGroupTerm,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.DENTAL_FOUND, dentalFound,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.NEW_GROUPS_AND_UPSELLS_QUEUE, newGroupsAndUpsellsQueue,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.PRE_WORK, preWork,staticVariableClass.assertEquals);  
        System.assertEquals(staticVariableClass.ERROR, error,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.HPCCCODE_PRODUCT_NAME, hpccProductName,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.HPCCCODE, hpcccode,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.FUNDING_TYPE, fundingType,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.STATE, state,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.INCENTIVE_TYPE_NA, incentiveTypeNA,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.INCENTIVE_TYPE_GC, incentiveTypeGC,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.INCENTIVE_TYPE_AD, incentiveTypeAD,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.RELATIONSHIP_TYPE, relationType ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CHILD_NUMBER, childNumber ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.GROUP_SIZE_0_50, grpsize050,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.GROUP_SIZE_51_99, grpsize5199,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.GROUP_SIZE_100_249, grpsize100249,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.GROUP_SIZE_250_499, grpsize250499,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.GROUP_SIZE_500_999, grpsize500999,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.GROUP_SIZE_1000, grpsize1000,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.QLI_TRIGGERNAM_AFTERINSERT, qliTriggerName ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.UPSELL, upsell,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.AHG_PRODUCT_NAME, aHGName,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.AHG_RECORDTYPE, aHGrecordType ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.QLI_AFTER_INSERT_TRIGGER, qliAfterInsertTrigger ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CLASS_LG_ASSOCIATE_PACKAGE_TO_PLAN  ,clasAssociatePkgToPlan, staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.ASSOCIATE_NEW_PKG,associateNewPkg   ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.ASSOCIATE_EXISTING_PKG,associateExistingPkg ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.PARENT_PRODUCT,parentProd,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.SELECTED_PARENT_PRODUCT,selectedParentProd  ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CHILD_BUNDLES,childBundle,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CHILD_LIST,childList,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CURRENT_PLAN,currentPlan,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.INCENTIVE_TYPE,incentiveType,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.INCENTIVE_TYPE_SELECT,incentiveTypeSelect   ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.TRUE_STRING,trueString,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.PLAN_LIST,planList,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.PRODUCT_SELECTION,productSelection,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.COMMERCIAL_SELECTIONS,commercialSelection,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.COMMERCIAL_FLOW ,commercialFlow,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.COMMERCIAL_CLINICAL,commercialClinical,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.PARENT_PRODUCT_ID,parentProdId,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.COMMERCIAL_CLINICAL_NODE,commercialClinicalNode ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.FINAL_PROGRAM_LIST,finalPgmList,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.COMMERCIAL_BUY_UPS,commercialBuyUp,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.COMMERCIAL_BUYUP_SELECTION,commercialBuyUpSelection ,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.PROGRAM ,program,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.PRODUCT_CATEGORY,prodCategory,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.LOCAL_RENEWAL,localRenewal,staticVariableClass.assertEquals);
        //HW Indicator
        System.assertEquals(staticVariableClass.COMPLETED,completed,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.FAILED,failed,staticVariableClass.assertEquals);
        //LGSMERecordCreation
        System.assertEquals(staticVariableClass.WGS_CLAIM_SYSTEM,wgsClaimSystem,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.VIEW_STRING,viewString,staticVariableClass.assertEquals);
        
        //Gladiators - sprint 201.1 - PRDCRM : 50723
        System.assertEquals(staticVariableClass.POOLED,pooled,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.STANDARD,standard,staticVariableClass.assertEquals);
        
        //PRDCRM-50634 - GLD - 201.2
        System.assertEquals(staticVariableClass.MODIFY,sModify,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.STATE_REGULATOR,sStateRegulator,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.HCR_STATUS,sHcrStatus,staticVariableClass.assertEquals);
        
        //PRDCRM-49125 - Vikings - 201.3
        
        String sWithdrawn        =  staticVariableClass.WITHDRAWN;
        String sApproved     =  staticVariableClass.APPROVED;
        String sUnderwritingError      =  staticVariableClass.UNDERWRITING_ERROR;
        
        System.assertEquals(staticVariableClass.WITHDRAWN,sWithdrawn,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.APPROVED,sApproved,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.UNDERWRITING_ERROR,sUnderwritingError,staticVariableClass.assertEquals);
        
        //PRDCRM-51890 - Send parameters to P2A on Create CEP Case Button from QLI
        System.assertEquals(staticVariableClass.BENEFIT,sBenefit,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CALENDAR,sCalendar,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CEP_CASE,sCEPCase,staticVariableClass.assertEquals);
        
        System.assertEquals(staticVariableClass.ASO,sAso,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.FI,sFi,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.N_A,sNa,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.ASO_FI,sAsoFi,staticVariableClass.assertEquals);
        
        //GLD - PRDCRM:50840 - Auto create L&D SME for Supplemental Health Products
        System.assertEquals(staticVariableClass.HOSPITAL_INDEMNITY,sHospIndemnity,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.ACCIDENT,sAccident,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.CRITICAL_ILLNESS,sCriticalIll,staticVariableClass.assertEquals);
        
        //XMEN - PRDCRM-51773 - PGs: LWC UI/UX for filtering PG Catalog Item (Component 1)
        String sImplementation  =  staticVariableClass.IMPLEMENTATION;
        String sOperations =  staticVariableClass.OPERATIONS;
        System.assertEquals(staticVariableClass.IMPLEMENTATION,sImplementation,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.OPERATIONS,sOperations,staticVariableClass.assertEquals);
        
        //GLD - PRDCRM - 52626 : Plan Update Screen and Quote Plan Card Update
        System.assertEquals(staticVariableClass.VISION_PLANS,sVisionPlan,staticVariableClass.assertEquals);
        
        //APEX CPU Time Out Issue Fix
        String sFixed  =  staticVariableClass.FIXED;
        String sHwLiveHealth =  staticVariableClass.HW_LIVE_HEALTH_ONLINE;
        String sNationalAcc  =  staticVariableClass.NATIONAL_ACCOUNTS;
        String sJeopardy =  staticVariableClass.JEOPARDY;
        String shundredPercent  =  staticVariableClass.HUNDRED_PERCENT;
        String sFiftyPercent =  staticVariableClass.FIFTY_PERCENT;
        String sTenPercent  =  staticVariableClass.TEN_PERCENT;
        String sApiuser =  staticVariableClass.API_USER;
        String sDead =  staticVariableClass.DEAD;
        String sIgapDead =  staticVariableClass.IGAP_DEAD;
        String sIgaplost =  staticVariableClass.IGAP_LOST;
        String sLost =  staticVariableClass.LOST;
        String sIgapInProgress =  staticVariableClass.IGAP_IN_PROGRESS;
        
        System.assertEquals(staticVariableClass.FIXED,sFixed,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.HW_LIVE_HEALTH_ONLINE,sHwLiveHealth,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.NATIONAL_ACCOUNTS,sNationalAcc,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.JEOPARDY,sJeopardy,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.HUNDRED_PERCENT,shundredPercent,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.FIFTY_PERCENT,sFiftyPercent,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.TEN_PERCENT,sTenPercent,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.API_USER,sApiuser,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.DEAD,sDead,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.IGAP_DEAD,sIgapDead,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.IGAP_LOST,sIgaplost,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.LOST,sLost,staticVariableClass.assertEquals);
        System.assertEquals(staticVariableClass.IGAP_IN_PROGRESS,sIgapInProgress,staticVariableClass.assertEquals);
        
    } 
}