/***
Static Variable Class
Usage : Replace hardcoded values
***/

public virtual class staticVariableClass {
    
    // String Variables
    public static String StageNameInitiated {get {return 'Initiated';} }
    public static String RenewalLocal {get {return ' Renewal Local-';} }
    public static String RenewalLocal1 {get {return 'Renewal Local';} }
    public static String IGAPSold {get {return 'IGAP Sold';} }
    public static String Renewed {get {return 'Renewed';} }
    public static String Notrenewingincurrentperiod {get {return 'Not renewing in Current Period';} }
    public static String NewBusinessLocal {get {return 'New Business Local';} }
    public static String NewBusinessLocalhyphen {get {return 'New Business Local-';} }
    public static String Sold {get {return 'Sold';} }
    public static String IGAPLocal {get {return 'In Group Add Product Local';} }
    public static String IGCLocal {get {return 'In Group Change Local';} }
    public static String SoldRenewed {get {return 'Sold/Renewed';} }
    public static String InProgress {get {return 'In Progress';} }
    public static String RecordsProcessed {get {return 'records processed : ';} }
    public static String NumberOfErrors {get {return 'Number Of Errors : ';} }
    public static String String_cronexpression {get {return '0  00 1 3 * ?';} }
    public static String SIC {get {return '1234';} }
    public static String AccountName {get {return 'Sahil Test';} }
    public static String Entity {get {return 'Local/Large Group';} }
    public static String Region {get {return 'Central';} }
    public static String UniCare {get {return 'UniCare';} }
    public static String size {get {return '100 - 249';} }
    
    public static Decimal emp {get {return 100;} }
    public static String AK {get {return 'AK';} }
    public static String California {get {return 'California';} }
    public static String Maine {get {return 'Maine';} }
    public static String Connecticut {get {return 'Connecticut';} }
    public static String Georgia {get {return 'Georgia';} }
    public static String Indiana {get {return 'Indiana';} }
    public static String ClosedWon {get {return 'Closed Won';} }
    public static String TeamMemberRole {get {return 'Account Executive';} }
    public static String TEAM_ROLE_GRS_ACCOUNT_EXECUTIVE{get {return 'GRS Account Executive';} }
    public static String TEAM_ROLE_GRS_ESR{get {return 'GRS ESR';} }
    public static String TEAM_ROLE_VOLUNTARY_ENROLLMENT{get {return 'Voluntary Enrollment Consultant';} }
    public static String DNCError{get {return 'You must attach documentation on this record to be able to approve it.';} }
    public static String DNCTstAcc{get {return 'Test Account';} }
    public static String DNCTstAccState{get {return 'Colorado';} }
    public static String DNCTstEntity{get {return 'Local/Large Group';} }
    public static String DNCTstAcc2{get {return 'Test Account2';} }
    public static String DNCStrBefore{get {return 'Testing base 64 encode';} }
    public static String DNCStrTitle{get {return 'test content trigger';} }
    public static String DNCStrPath{get {return 'test';} }
    public static String DNCStrShareType{get {return 'V';} }
    public static String DNCStatusPen{get {return 'Pending Approval';} }
    public static String DNCStatusNew{get {return 'New';} }
    public static String DNCStatusApproved{get {return 'Approved';} }
    public static String DNCStrGrpPref{get {return 'Test Group Preference Comment';} }
    public static String DNCStrGrp{get {return 'Group';} }
    public static String DNCStrAccManager{get {return 'Account Manager';} }
    public static String DNCStrEmpPref{get {return 'Employer Preference';} }
    public static String String_CarveCron_Exp1  {get {return '0 0 * * * ?';} }
    public static String String_CarveCron_Exp2  {get {return '0 30 * * * ?';} } 
    public static String LgQliUpdateProdStage {get {return 'Declined to Quote';}}
    public static String LgQliUpdateProdProbability {get {return '0%';}}
    public static String testAccBillingStreet {get {return 'Land Mark';}}
    public static String testAccBillingPostalCode {get {return '636111';}}
    public static String testAccBillingCity {get {return 'Bangalore';}}
    public static String testAccBillingCountry {get {return 'India';}}
    public static String testAccBillingState {get {return 'Karnataka';}}
    public static String testProdName {get {return 'Anthem Health Guide';}}
    public static String testProdTermYearsLeft {get {return '5';}}
    public static String CreateGrpGETGROUPNUMBER  {get {return 'getGroupNumber';}}
    public static String CreateGrpUPDATENEXTNUMBERUTILITY  {get {return 'updateNextNumberUtility';}}
    public static String CreateGrpSTATUSCODE {get {return 'StatusCode';}}
    public static String CreateGrpSUCCESS  {get {return 'Success';}}
    public static String CreateGrpFAILURE  {get {return 'Failure';}}
    public static String CreateGrpERRMSG  {get {return 'Errormsg';}}
    public static String CreateGrpREQUESTGROUPNUMBERSTEP  {get {return 'RequestGroupNumberStep';}}
    public static String CreateGrpACCTID  {get {return 'acctId';}}
    public static String CreateGrpGROUPNUMBER  {get {return 'GroupNumber';}}
    public static String CreateGrpWARNINGFLAG  {get {return 'WarningFlag';}}
    public static String CreateGrpERROR  {get {return 'error';}}
    public static String CreateGrpLASTNUMBEREMPTY  {get {return 'Last used number is empty for this state, Please enter it manually';}}
    public static String CreateGrpNOSTATERECORD  {get {return 'Could not find last used number, Please enter it manually';}}
    public static String CreateGrpGROUPNUMBERALREADYINUSE   {get {return 'This Group number is already in use';}}
    public static String CreateGrpQUOTEID   {get {return 'ContextId';}}
    public static String CreateGrpCLAIMSYSTEM   {get {return 'ClaimSystem';}}
    public static String CreateGrpLOB   {get {return 'LineOfBusiness';}}
    public static String DeleteQliGETQLI    {get {return 'getQLI';}}
    public static String DeleteQliGETQLIPlans    {get {return 'getQLIPlans';}}
    public static String DeleteQliSPLITRECORDSELECTION    {get {return 'SplitRecordSelection';}}
    public static String DeleteQliQLIPRODLIST   {get {return 'QLIProdList';}}
    public static String DeleteQliQLIID    {get {return 'Id';}}
    public static String QUOTE_ID    {get {return 'QuoteId';}}
    
    public static String CreateGroupNumberGAReset {get {return '0000';} } // CreateGroupNumber
    public static Integer CreateGroupNumberDigits {get {return 4;} } //// CreateGroupNumber
    public static String CreateGroupNumberNH {get {return 'New Hampshire';} } //// CreateGroupNumber
    public static String CreateGroupNumberNH1 {get {return 'NewHampshire';} } //// CreateGroupNumber
    
    
    public static String TBD {get{ return 'TBD';}}
    public static String GroupNum {get{ return '123';}}
    public static String AnthemHealthGuide {get{ return 'Anthem Health Guide';}}
    public static String NumericFive {get{ return '5';}}
    public static String OpportunityName{get{ return 'abc';}}
    public static String OpportunityStageName{get{ return '0';}}
    public static String userLastName{get{ return 'LIVESTON1234';}}
    public static String userFirstName{get{ return 'JASON';}}
    public static String userAlias{get{ return 'jliv';}}
    public static String userEmail{get{ return 'jason.liveston@asdf1234.com';}}
    public static String userUsername{get{ return 'jason.liveston@asdf1234.com';}}
    public static String userTimeZoneSidKey{get{ return 'GMT';}}
    public static String userLanguageLocaleKey{get{ return 'en_US';}}
    public static String userEmailEncodingKey{get{ return 'UTF-8';}}
    public static String userLocaleSidKey{get{ return 'en_US';}}
    public static boolean stopTrigger=false;
    
    
    public static String LocalNASCOandWGS {get{ return 'Local NASCO and WGS';}}
    public static String WorkInProgress {get{ return '02 Work In Progress';}}
    public static String PendingSmeReview {get{ return 'Pending SME Review';}}
    public static String LocalImplementations {get{ return 'Local Implementations';}} 
    public static String LGChangeRequestOffCycle {get{ return 'LG Change Request Off Cycle';}} 
    public static String ChangeRequestOffCycle {get{ return 'Change Request Off Cycle';}}
    public static String UpsellNo {get{ return 'No';}}
    public static String UpsellYes {get{ return 'Yes';}}
    public static String Termone {get{ return '1';}}
    public static String Dental {get{ return 'Dental';}}
    public static String Vision {get{ return 'Vision';}}
    public static String Life {get{ return 'Life';}}
    public static String Disability {get{ return 'Disability';}}
    public static Decimal QuantityOrPrice {get{ return 1.0 ;}}
    public static String JAANASCOandWGS {get{ return 'JAA NASCO and WGS';}}
    public static String MCSNASCOandWGS {get{ return 'MCS NASCO and WGS';}}
    public static String AIMTesting03 {get{ return 'AIMTesting03';}} 
    public static String AIMTesting02 {get{ return 'AIMTesting02';}}
    public static String AIMTesting01 {get{ return 'AIMTesting01';}}
    public static String Order {get{ return 'Order';}}
    public static String Account {get{ return 'Account';}}
    public static String Opportunity {get{ return 'Opportunity';}}
    public static String NewBusiness {get{ return 'New Business';}}
    public static String LocalNewBusiness {get{ return 'Local New Business';}}
    public static String ReadyforImps {get{ return 'Ready for Imps';}}
    public static String LGProspect {get{ return 'LG Prospect';}}
    public static String AnthemDentalProdName {get{ return 'Anthem Dental';}}
    public static String AnthemLifeProdName {get{ return 'Anthem LifeProd';}}
    public static String Draft {get{ return 'Draft';}}
    public static String Medical {get{ return 'Medical';}}
    public static String Renew {get{ return 'Renew';}}
    public static String SubscribersRollup {get{ return 'Subscribers_Rollup__c';}}
    public static String MembersRollup {get{ return 'Members_Rollup__c';}}
    public static String TotalMedicalSubscribers {get{ return 'Total_Medical_Subscribers__c';}}
    public static String TotalMedicalMembers {get{ return 'Total_Medical_Members__c';}}
    //LGSMERecordCreation Class-->GenerateIdCardMethod, Static values.
    public static String defaultIDCardStage {get{ return '01 Not Started';}}
    //Plan Mass Update
    public static String Product {get{ return 'Product';}}
    public static String Plan {get{ return 'Plan';}}
    public static String OppType {get{ return 'OppType__c';}}
    public static String ProductStage {get{ return 'ProductStage__c';}}
    public static String RecordType {get{ return 'RecordType__c';}}
    public static String Reason {get{ return 'Reason__c';}}
    public static String slash {get{ return '/';}}
    public static String assertEquals {get{return 'Assert Equals Passed Successfully';}}
    public static String assertNotEquals {get{ return 'Assert Not Equals Passed Successfully';}}
    public static String SYSTEM_ADMIN {get{ return 'System Administrator';}}
    public static String TERMED {get{return 'Termed';}}
    public static String RENEWAL {get{return 'Renewal';}}
    public static String FULL_GROUP_TERM {get{return 'Full Group Term';}}
    public static String LTD_PROD_TYPE {get{return 'LTD';}}
    public static String STD_PROD_TYPE {get{return 'STD';}}
    public static String DENTAL_FOUND {get{return 'Dental found';}}
    public static String VISION_FOUND {get{return 'Vision found';}}
    public static String LIFE_FOUND {get{return 'Life found';}}
    public static String DISABILITY_FOUND {get{return 'Disability found';}}
    public static String QUEUE {get{return 'Queue';}}
    public static String NEW_GROUPS_AND_UPSELLS_QUEUE {get{return 'New_groups_and_Upsells_Queue';}}
    public static String USER_ID_FORMAT {get{return '00G';}}
    public static String STAGE04_APPROVED {get{return '04 Approved';}}
    public static String LOCAL {get{return 'Local';}}
    public static String COMMERCIAL_SALES_STRING {get{return 'Commercial Sales';}}
    public static String LG_SME_RECORD_CREATION_STRING {get{return 'LGSMERecordCreation';}}
    public static String AFTER_UPDATE_STRING {get{return 'AfterUpdate';}}
    public static String PRE_WORK {get{return 'Pre Work';}}
    public static String PRODUCT_CATEGORY {get{return 'Product';}}
    public static String CLASS_LG_QUOTE_LINE_ITEM {get{return 'LGHWQuoteLineItemActions';}}
    public static String CREATE_HW_PACKAGE_PROGRAMS  {get{return 'createHWPackagePrograms';}}
    public static String CREATE_HWPACKAGE_PROGRAMS_FUTURE {get{return 'createHWPackageProgramsFuture';}}
    public static String PLAN_LIST {get{return 'trueArr';}}
    public static String PRODUCT_SELECTION {get{return 'ProductSelection';}}
    public static String COMMERCIAL_SELECTIONS {get{return 'Commercial_Selections';}}
    public static String COMMERCIAL_FLOW {get{return 'CommercialFlow';}}
    public static String COMMERCIAL_CLINICAL {get{return 'Commercial Clinical';}}
    public static String PARENT_PRODUCT_ID {get{return 'ParentProductId';}}
    public static String COMMERCIAL_CLINICAL_NODE {get{return 'Commercial_Clinical';}}
    public static String FINAL_PROGRAM_LIST {get{return 'FixList';}}
    public static String COMMERCIAL_BUY_UPS {get{return 'Commercial Buy-Ups';}}
    public static String COMMERCIAL_BUYUP_SELECTION {get{return 'Commercial_BuyUpSelection';}}
    public static String PROGRAM {get{return 'Program';}}
    public static String ERROR {get{return 'ERROR';}}
    public static String HPCCCODE_PRODUCT_NAME {get{return 'Pack123';}}
    public static String HPCCCODE {get{return 'HM09';}}
    public static String FUNDING_TYPE{get{return 'FI';}}
    public static String STATE{get{return 'CA';}}
    public static String INCENTIVE_TYPE_NA{get{return 'NA';}}
    public static String INCENTIVE_TYPE_GC{get{return 'GC';}}
    public static String INCENTIVE_TYPE_AD{get{return 'AD';}}
    public static String RELATIONSHIP_TYPE{get{return 'Child';}}
    public static String CHILD_NUMBER{get{return '1';}}
    public static String GROUP_SIZE_0_50{get{return '0 - 50';}}
    public static String GROUP_SIZE_51_99{get{return '51 - 99';}}
    public static String GROUP_SIZE_100_249{get{return '100 - 249';}}
    public static String GROUP_SIZE_250_499{get{return '250 - 499';}}
    public static String GROUP_SIZE_500_999{get{return '500 - 999';}}
    public static String GROUP_SIZE_1000{get{return '1000+';}}
    public static String QLI_TRIGGERNAM_AFTERINSERT{get{return 'QuoteLineItemAfterInsert';}}
    public static String UPSELL{get{ return 'Upsell__c';}}
    public static String AHG_PRODUCT_NAME{get{return 'ANTHEM HEALTH GUIDE';}}
    public static String AHG_RECORDTYPE{get{return 'Anthem Health Guide';}}
    public static String QLI_AFTER_INSERT_TRIGGER{get{return 'ANA_QuoteLineItemsAfterCreate';}} 
    public static String CLASS_LG_ASSOCIATE_PACKAGE_TO_PLAN {get{return 'LGHWAssociatePackageToPlansController';}} 
    public static String ASSOCIATE_NEW_PKG {get{return 'associateNewPkg';}}
    public static String ASSOCIATE_EXISTING_PKG {get{return 'associateExistingPkg';}}
    public static String PARENT_PRODUCT{get{return 'Parent_Product';}}
    public static String SELECTED_PARENT_PRODUCT {get{return 'SelectedParentProduct';}}
    public static String CHILD_BUNDLES{get{return 'Child_Bundles';}}
    public static String CHILD_LIST{get{return 'ChildList';}}
    public static String CURRENT_PLAN{get{return 'CurrentPlan';}}
    public static String INCENTIVE_TYPE{get{return 'IncentiveType';}}
    public static String INCENTIVE_TYPE_SELECT{get{return 'IncentiveTypeSelect';}}
    public static String TRUE_STRING {get{return 'True';}}
    public static String LOCAL_RENEWAL {get{return 'Local Renewal';}}
    //HW Indicator 
    public static String COMPLETED {get{return 'Completed';}}
    public static String FAILED {get{return 'Failed';}}
    public static String APEXCLASSNAME {get{return 'TESTCLASSNAME';}}
    public static String WGS_CLAIM_SYSTEM {get{return 'WGS 2.0';}} 
    
    
    //Start: 46384, LGSMERecordCreation
    public static final String RECORD_PROCESSED_SUCCESS{get{return 'Success';}}
    public static final String RECORD_PROCESSED_FAILED{get{return 'Failed';}}
    public static final String BATCH_RENEWAL_STATUS{get{return 'BatchRenewalStatus';}}
    //Stop: 46384
    public static final String VIEW_STRING{get{return 'View';}}
    
    //Gladiators - sprint 201.1 - PRDCRM : 50723
    public static final String POOLED{get{return 'Pooled';}}
    public static final String STANDARD{get{return 'Standard';}}

    //PRDCRM-51249 by GLD 
    public static final String MODIFIED{get{return 'Modified';}}
    public static final String CUSTOM{get{return 'Custom';}}
    
    //PRDCRM-50634 - GLD - 201.2
    public static final String MODIFY{get{return 'Modify';}}
    public static final String HCR_STATUS{get{return 'Grandfathered';}}
    public static final String STATE_REGULATOR{get{return 'DMHC-200C';}} 
    
    //PRDCRM-49125 - Vikings - 201.3
    public static final String WITHDRAWN{get{return 'Withdrawn';}}
    public static final String APPROVED{get{return '04 Approved';}}
    public static final String UNDERWRITING_ERROR{get{return 'Implementation Status cannot be marked as Withdrawn if associated Underwriting SME is Approved';}}
    
    //-GLD-PRDCRM-51890 - Send parameters to P2A on Create CEP Case Button from QLI
     public static final String BENEFIT {get{return 'Benefit';}}
     public static final String CALENDAR {get{return 'Calendar';}}
     public static final String CEP_CASE {get{return 'CEPCase';}}
    
     //PRDCRM-50802 - GLD 201.4
    public static String ASO{get {return 'ASO';} }
    public static String FI{get {return 'FI';} }
    public static String N_A{get {return 'N/A';} }
    public static String ASO_FI{get {return 'ASO/FI';} }
    
    //GLD - PRDCRM:50840 - Auto create L&D SME for Supplemental Health Products
    public static String HOSPITAL_INDEMNITY {get {return 'Hospital Indemnity';} }
    public static String ACCIDENT {get {return 'Accident';} }
    public static String CRITICAL_ILLNESS{get {return 'Critical Illness';} }
    
    //XMEN - PRDCRM-51773 - PGs: LWC UI/UX for filtering PG Catalog Item (Component 1)
    public static String IMPLEMENTATION {get {return 'Implementation';} }
    public static String OPERATIONS{get {return 'Operations';} }
    
    //PRDCRM - 52626 : Plan Update Screen and Quote Plan Card Update
    public static String VISION_PLANS {get {return 'Vision Plans';}}
    
     //APEX CPU Time Out Issue Fix
     public static String FIXED {get {return 'Fixed';}}
     public static String HW_LIVE_HEALTH_ONLINE {get {return 'Health and Wellness - Live Health Online';}}
     public static String NATIONAL_ACCOUNTS {get {return 'National Accounts';}}
     public static String JEOPARDY {get {return 'Jeopardy';}}
     public static String HUNDRED_PERCENT {get {return '100%';}}
     public static String FIFTY_PERCENT {get {return '50%';}}
     public static String TEN_PERCENT {get {return '10%';}}
     public static String API_USER {get {return 'API User';}}
     public static String DEAD {get {return 'Dead';}}
     public static String IGAP_DEAD {get {return 'IGAP Dead';}}
     public static String IGAP_LOST {get {return 'IGAP Lost';}}
     public static String LOST {get {return 'Lost';}}
     public static String IGAP_IN_PROGRESS {get {return 'IGAP In Progress';}}
         
}