@isTest
public class wellpointComServiceUtility_Test {

  static testmethod void SubmitFIRSTQuoteRequest_element_Test(){
    wellpointComServiceUtility.SubmitFIRSTQuoteRequest_element sfqre = new wellpointComServiceUtility.SubmitFIRSTQuoteRequest_element();
    system.debug(sfqre.Account);
  }
  
  static testmethod void Competitor_Test(){
    wellpointComServiceUtility.Competitor comp = new wellpointComServiceUtility.Competitor();
  }
  
  static testmethod void status_Test(){
    wellpointComServiceUtility.Status status = new wellpointComServiceUtility.Status();
  }
  
  static testmethod void quote_Test(){
    wellpointComServiceUtility.Quote quote = new wellpointComServiceUtility.Quote();
  }
  
  static testmethod void Broker_Test(){
    wellpointComServiceUtility.Broker broker = new wellpointComServiceUtility.Broker();
  }
  
  static testmethod void opportunity_Test(){
    wellpointComServiceUtility.Opportunity opp = new wellpointComServiceUtility.Opportunity();
  }
  
  static testmethod void Address_Test(){
    wellpointComServiceUtility.Address add = new wellpointComServiceUtility.Address();
  }
  
  static testmethod void Account_Test(){
    wellpointComServiceUtility.Account acc = new wellpointComServiceUtility.Account();
  }
  
  static testmethod void UtilityService_SubmitFIRSTQuote_ResponseType_Test(){
    wellpointComServiceUtility.UtilityService_SubmitFIRSTQuote_ResponseType sfqrt = new wellpointComServiceUtility.UtilityService_SubmitFIRSTQuote_ResponseType();
  }
  
  static testmethod void UtilityService_SubmitFIRSTQuote_RequestType_Test(){
    wellpointComServiceUtility.UtilityService_SubmitFIRSTQuote_RequestType sfqrt = new wellpointComServiceUtility.UtilityService_SubmitFIRSTQuote_RequestType();
  }
  
  static testmethod void QuoteLineItem_Test(){
    wellpointComServiceUtility.QuoteLineItem qli = new wellpointComServiceUtility.QuoteLineItem();
  }
  
  static testmethod void SubmitFIRSTQuoteResponse_element_Test(){
    wellpointComServiceUtility.SubmitFIRSTQuoteResponse_element sfqre = new wellpointComServiceUtility.SubmitFIRSTQuoteResponse_element();
  }
}