@isTest
public class wellpointComEsbContext_test {
  
  static testmethod void UsernameTokenType_Test() {
    wellpointComEsbContext.UsernameTokenType utt = new wellpointComEsbContext.UsernameTokenType();
  }
  
  static testmethod void PropertyType_Test() {
    wellpointComEsbContext.PropertyType pt = new wellpointComEsbContext.PropertyType();
  }
  
  static testmethod void CtxPropsType_Test() {
    wellpointComEsbContext.CtxPropsType cpt = new wellpointComEsbContext.CtxPropsType();
  }
  
  static testmethod void CtxProps_element_Test() {
    wellpointComEsbContext.CtxProps_element cpe = new wellpointComEsbContext.CtxProps_element();
  }
  
  static testmethod void ContextType_Test() {
    wellpointComEsbContext.ContextType ct = new wellpointComEsbContext.ContextType();
  }
  
  static testmethod void Security_element_Test() {
    wellpointComEsbContext.Security_element se = new wellpointComEsbContext.Security_element();
  }
  
  static testmethod void Property_element_Test() {
    wellpointComEsbContext.Property_element pe = new wellpointComEsbContext.Property_element();
  }
}