<div class="modal-header">
    <h4 class="modal-title">Save As Attachment</h4>
    <img class="modal-header-close-button" ng-src="{{closeIconUrl}}" ng-click="dialogClose()"/>
</div>
<div class="modal-body clearfix">
	<seismic-busy is-busy="isSaving" wrapper-class="'email-busy-cover'">
    </seismic-busy>

    <div style="height: 100px;">
        Click "Save" to save document as attachment of current record.
    </div>

    <button class="btn pull-right" ng-click="save()">Save</button>
</div>