<div class="modal-header">
    <h4 class="modal-title">Create Content</h4>
    <img class="modal-header-close-button" ng-src="{{closeIconUrl}}" ng-click="dialogClose()"/>
</div>
<div class="modal-body clearfix">
	<seismic-busy is-busy="isCreating" wrapper-class="'email-busy-cover'">
    </seismic-busy>

    <div style="height: 100px;">
        Click "Create Content" to create a content.
    </div>

    <button class="btn pull-right" ng-click="createContent()">Create Content</button>
</div>