<div class="modal-header">
    <h4 class="modal-title">{{modalTitle}}</h4>
    <img class="modal-header-close-button" ng-src="{{closeIconUrl}}" ng-click="dialogClose()"/>
</div>
<div class="modal-body">
    <modal-transclude></modal-transclude>
</div>
<div class="modal-footer">
    <button class="btn btn-primary" ng-show="okBtnVisible" ng-click="ok()">OK</button>
    <button class="btn btn-warning" ng-show="cancelBtnVisible" ng-click="cancel()">Cancel</button>
</div>