[
  {
    "parent":"JobFunction",
    "groups":{
      "JobFunctionMedicalHealthEmployees":[
        {
          "value":"#5_plus_medical_and_health",
          "displayLabel":"5+ medical/health employees",
          "searchString":"5 medical health employees",
          "description":"This company has 5 or more employees in a medical or health role",
          "group":"MedicalHealthEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_medical_and_health",
          "displayLabel":"2+ medical/health employees",
          "searchString":"2 medical health employees",
          "description":"This company has 2 or more employees in a medical or health role",
          "group":"MedicalHealthEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_medical_and_health",
          "displayLabel":"250+ medical/health employees",
          "searchString":"250 medical health employees",
          "description":"This company has 250 or more employees in a medical or health role",
          "group":"MedicalHealthEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_medical_and_health",
          "displayLabel":"1000+ medical/health employees",
          "searchString":"1000 medical health employees",
          "description":"This company has 1000 or more employees in a medical or health role",
          "group":"MedicalHealthEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_medical_and_health",
          "displayLabel":"25+ medical/health employees",
          "searchString":"25 medical health employees",
          "description":"This company has 25 or more employees in a medical or health role",
          "group":"MedicalHealthEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_medical_and_health",
          "displayLabel":"10+ medical/health employees",
          "searchString":"10 medical health employees",
          "description":"This company has 10 or more employees in a medical or health role",
          "group":"MedicalHealthEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_medical_and_health",
          "displayLabel":"100+ medical/health employees",
          "searchString":"100 medical health employees",
          "description":"This company has 100 or more employees in a medical or health role",
          "group":"MedicalHealthEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_medical_and_health",
          "displayLabel":"500+ medical/health employees",
          "searchString":"500 medical health employees",
          "description":"This company has 500 or more employees in a medical or health role",
          "group":"MedicalHealthEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_medical_and_health",
          "displayLabel":"50+ medical/health employees",
          "searchString":"50 medical health employees",
          "description":"This company has 50 or more employees in a medical or health role",
          "group":"MedicalHealthEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionGeneralManagementEmployees":[
        {
          "value":"#50_plus_general_management",
          "displayLabel":"50+ general management emloyees",
          "searchString":"50 general management employees",
          "description":"This company has 50 or more employees in a general management role",
          "group":"GeneralManagementEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_general_management",
          "displayLabel":"1000+ general management employees",
          "searchString":"1000 general management employees",
          "description":"This company has 1000 or more employees in a general management role",
          "group":"GeneralManagementEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_general_management",
          "displayLabel":"2+ general management employees",
          "searchString":"2 general management employees",
          "description":"This company has 2 or more employees in a general management role",
          "group":"GeneralManagementEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_general_management",
          "displayLabel":"250+ general management employees",
          "searchString":"250 general management employees",
          "description":"This company has 250 or more employees in a general management role",
          "group":"GeneralManagementEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_general_management",
          "displayLabel":"25+ general management employees",
          "searchString":"25 general management employees",
          "description":"This company has 25 or more employees in a general management role",
          "group":"GeneralManagementEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_general_management",
          "displayLabel":"100+ general management employees",
          "searchString":"100 general management employees",
          "description":"This company has 100 or more employees in a general management role",
          "group":"GeneralManagementEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_general_management",
          "displayLabel":"10+ general management employees",
          "searchString":"10 general management employees",
          "description":"This company has 10 or more employees in a general management role",
          "group":"GeneralManagementEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_general_management",
          "displayLabel":"500+ general management employees",
          "searchString":"500 general management employees",
          "description":"This company has 500 or more employees in a general management role",
          "group":"GeneralManagementEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_general_management",
          "displayLabel":"5+ general management employees",
          "searchString":"5 general management employees",
          "description":"This company has 5 or more employees in a general management role",
          "group":"GeneralManagementEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionLegalEmployees":[
        {
          "value":"#250_plus_legal",
          "displayLabel":"250+ legal employees",
          "searchString":"250 legal employees",
          "description":"This company has 250 or more employees in a legal role",
          "group":"LegalEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_legal",
          "displayLabel":"2+ legal employees",
          "searchString":"2 legal employees",
          "description":"This company has 2 or more employees in a legal role",
          "group":"LegalEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_legal",
          "displayLabel":"1000+ legal employees",
          "searchString":"1000 legal employees",
          "description":"This company has 1000 or more employees in a legal role",
          "group":"LegalEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_legal",
          "displayLabel":"500+ legal employees",
          "searchString":"500 legal employees",
          "description":"This company has 500 or more employees in a legal role",
          "group":"LegalEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_legal",
          "displayLabel":"5+ legal employees",
          "searchString":"5 legal employees",
          "description":"This company has 5 or more employees in a legal role",
          "group":"LegalEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_legal",
          "displayLabel":"50+ legal employees",
          "searchString":"50 legal employees",
          "description":"This company has 50 or more employees in a legal role",
          "group":"LegalEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_legal",
          "displayLabel":"25+ legal employees",
          "searchString":"25 legal employees",
          "description":"This company has 25 or more employees in a legal role",
          "group":"LegalEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_legal",
          "displayLabel":"10+ legal employees",
          "searchString":"10 legal employees",
          "description":"This company has 10 or more employees in a legal role",
          "group":"LegalEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_legal",
          "displayLabel":"100+ legal employees",
          "searchString":"100 legal employees",
          "description":"This company has 100 or more employees in a legal role",
          "group":"LegalEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionScientistsEmployees":[
        {
          "value":"#100_plus_scientists",
          "displayLabel":"100+ scientists",
          "searchString":"100 scientist employees",
          "description":"This company has 100 or more employees in a scientist role",
          "group":"ScientistsEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_scientists",
          "displayLabel":"25+ scientists",
          "searchString":"25 scientist employees",
          "description":"This company has 25 or more employees in a scientist role",
          "group":"ScientistsEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_scientists",
          "displayLabel":"10+ scientists",
          "searchString":"10 scientist employees",
          "description":"This company has 10 or more employees in a scientist role",
          "group":"ScientistsEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_scientists",
          "displayLabel":"1000+ scientists",
          "searchString":"1000 scientist employees",
          "description":"This company has 1000 or more employees in a scientist role",
          "group":"ScientistsEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_scientists",
          "displayLabel":"500+ scientists",
          "searchString":"500 scientist employees",
          "description":"This company has 500 or more employees in a scientist role",
          "group":"ScientistsEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_scientists",
          "displayLabel":"5+ scientists",
          "searchString":"5 scientist employees",
          "description":"This company has 5 or more employees in a scientist role",
          "group":"ScientistsEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_scientists",
          "displayLabel":"50+ scientists",
          "searchString":"50 scientist employees",
          "description":"This company has 50 or more employees in a scientist role",
          "group":"ScientistsEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_scientists",
          "displayLabel":"250+ scientists",
          "searchString":"250 scientist employees",
          "description":"This company has 250 or more employees in a scientist role",
          "group":"ScientistsEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_scientists",
          "displayLabel":"2+ scientists",
          "searchString":"2 scientist employees",
          "description":"This company has 2 or more employees in a scientist role",
          "group":"ScientistsEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionSalesEmployees":[
        {
          "value":"#250_plus_sales",
          "displayLabel":"250+ sales employees",
          "searchString":"250 sales employees",
          "description":"This company has 250 or more employees in a sales role",
          "group":"SalesEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_sales",
          "displayLabel":"50+ sales employees",
          "searchString":"50 sales employees",
          "description":"This company has 50 or more employees in a sales role",
          "group":"SalesEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_sales",
          "displayLabel":"25+ sales employees",
          "searchString":"25 sales employees",
          "description":"This company has 25 or more employees in a sales role",
          "group":"SalesEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_sales",
          "displayLabel":"100+ sales employees",
          "searchString":"100 sales employees",
          "description":"This company has 100 or more employees in a sales role",
          "group":"SalesEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_sales",
          "displayLabel":"10+ sales employees",
          "searchString":"10 sales employees",
          "description":"This company has 10 or more employees in a sales role",
          "group":"SalesEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_sales",
          "displayLabel":"1000+ sales employees",
          "searchString":"1000 sales employees",
          "description":"This company has 1000 or more employees in a sales role",
          "group":"SalesEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_sales",
          "displayLabel":"500+ sales employees",
          "searchString":"500 sales employees",
          "description":"This company has 500 or more employees in a sales role",
          "group":"SalesEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_sales",
          "displayLabel":"2+ sales employees",
          "searchString":"2 sales employees",
          "description":"This company has 2 or more employees in a sales role",
          "group":"SalesEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_sales",
          "displayLabel":"5+ sales employees",
          "searchString":"5 sales employees",
          "description":"This company has 5 or more employees in a sales role",
          "group":"SalesEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionOperationsEmployees":[
        {
          "value":"#1000_plus_operations",
          "displayLabel":"1000+ operations employees",
          "searchString":"1000 operations employees",
          "description":"This company has 1000 or more employees in an operations role",
          "group":"OperationsEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_operations",
          "displayLabel":"250+ operations employees",
          "searchString":"250 operations employees",
          "description":"This company has 250 or more employees in an operations role",
          "group":"OperationsEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_operations",
          "displayLabel":"50+ operations employees",
          "searchString":"50 operations employees",
          "description":"This company has 50 or more employees in an operations role",
          "group":"OperationsEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_operations",
          "displayLabel":"100+ operations employees",
          "searchString":"100 operations employees",
          "description":"This company has 100 or more employees in an operations role",
          "group":"OperationsEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_operations",
          "displayLabel":"500+ operations employees",
          "searchString":"500 operations employees",
          "description":"This company has 500 or more employees in an operations role",
          "group":"OperationsEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_operations",
          "displayLabel":"5+ operations employees",
          "searchString":"5 operations employees",
          "description":"This company has 5 or more employees in an operations role",
          "group":"OperationsEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_operations",
          "displayLabel":"10+ operations employees",
          "searchString":"10 operations employees",
          "description":"This company has 10 or more employees in an operations role",
          "group":"OperationsEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_operations",
          "displayLabel":"25+ operations employees",
          "searchString":"25 operations employees",
          "description":"This company has 25 or more employees in an operations role",
          "group":"OperationsEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_operations",
          "displayLabel":"2+ operations employees",
          "searchString":"2 operations employees",
          "description":"This company has 2 or more employees in an operations role",
          "group":"OperationsEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionRecruiterEmployees":[
        {
          "value":"#100_plus_recruiters",
          "displayLabel":"100+ recruiters",
          "searchString":"100 recruiters",
          "description":"This company has 100 or more employees in a recruiter role",
          "group":"RecruiterEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_recruiters",
          "displayLabel":"25+ recruiters",
          "searchString":"25 recruiters",
          "description":"This company has 25 or more employees in a recruiter role",
          "group":"RecruiterEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_recruiters",
          "displayLabel":"2+ recruiters",
          "searchString":"2 recruiters",
          "description":"This company has 2 or more employees in a recruiter role",
          "group":"RecruiterEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_recruiters",
          "displayLabel":"250+ recruiters",
          "searchString":"250 recruiters",
          "description":"This company has 250 or more employees in a recruiter role",
          "group":"RecruiterEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_recruiters",
          "displayLabel":"1000+ recruiters",
          "searchString":"1000 recruiters",
          "description":"This company has 1000 or more employees in a recruiter role",
          "group":"RecruiterEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_recruiters",
          "displayLabel":"50+ recruiters",
          "searchString":"50 recruiters",
          "description":"This company has 50 or more employees in a recruiter role",
          "group":"RecruiterEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_recruiters",
          "displayLabel":"10+ recruiters",
          "searchString":"10 recruiters",
          "description":"This company has 10 or more employees in a recruiter role",
          "group":"RecruiterEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_recruiters",
          "displayLabel":"500+ recruiters",
          "searchString":"500 recruiters",
          "description":"This company has 500 or more employees in a recruiter role",
          "group":"RecruiterEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_recruiters",
          "displayLabel":"5+ recruiters",
          "searchString":"5 recruiters",
          "description":"This company has 5 or more employees in a recruiter role",
          "group":"RecruiterEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionDoctorEmployees":[
        {
          "value":"#10_plus_doctors",
          "displayLabel":"10+ doctors",
          "searchString":"10 doctor employees",
          "description":"This company has 10 or more employees in a doctor role",
          "group":"DoctorEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_doctors",
          "displayLabel":"25+ doctors",
          "searchString":"25 doctor employees",
          "description":"This company has 25 or more employees in a doctor role",
          "group":"DoctorEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_doctors",
          "displayLabel":"250+ doctors",
          "searchString":"250 doctor employees",
          "description":"This company has 250 or more employees in a doctor role",
          "group":"DoctorEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_doctors",
          "displayLabel":"1000+ doctors",
          "searchString":"1000 doctor employees",
          "description":"This company has 1000 or more employees in a doctor role",
          "group":"DoctorEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_doctors",
          "displayLabel":"2+ doctors",
          "searchString":"2 doctor employees",
          "description":"This company has 2 or more employees in a doctor role",
          "group":"DoctorEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_doctors",
          "displayLabel":"5+ doctors",
          "searchString":"5 doctor employees",
          "description":"This company has 5 or more employees in a doctor role",
          "group":"DoctorEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_doctors",
          "displayLabel":"100+ doctors",
          "searchString":"100 doctor employees",
          "description":"This company has 100 or more employees in a doctor role",
          "group":"DoctorEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_doctors",
          "displayLabel":"50+ doctors",
          "searchString":"50 doctor employees",
          "description":"This company has 50 or more employees in a doctor role",
          "group":"DoctorEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_doctors",
          "displayLabel":"500+ doctors",
          "searchString":"500 doctor employees",
          "description":"This company has 500 or more employees in a doctor role",
          "group":"DoctorEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionFinanceEmployees":[
        {
          "value":"#2_plus_finance",
          "displayLabel":"2+ finance employees",
          "searchString":"2 finance employees",
          "description":"This company has 2 or more employees in a finance role",
          "group":"FinanceEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_finance",
          "displayLabel":"5+ finance employees",
          "searchString":"5 finance employees",
          "description":"This company has 5 or more employees in a finance role",
          "group":"FinanceEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_finance",
          "displayLabel":"500+ finance employees",
          "searchString":"500 finance employees",
          "description":"This company has 500 or more employees in a finance role",
          "group":"FinanceEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_finance",
          "displayLabel":"50+ finance employees",
          "searchString":"50 finance employees",
          "description":"This company has 50 or more employees in a finance role",
          "group":"FinanceEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_finance",
          "displayLabel":"100+ finance employees",
          "searchString":"100 finance employees",
          "description":"This company has 100 or more employees in a finance role",
          "group":"FinanceEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_finance",
          "displayLabel":"10+ finance employees",
          "searchString":"10 finance employees",
          "description":"This company has 10 or more employees in a finance role",
          "group":"FinanceEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_finance",
          "displayLabel":"250+ finance employees",
          "searchString":"250 finance employees",
          "description":"This company has 250 or more employees in a finance role",
          "group":"FinanceEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_finance",
          "displayLabel":"1000+ finance employees",
          "searchString":"1000 finance employees",
          "description":"This company has 1000 or more employees in a finance role",
          "group":"FinanceEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_finance",
          "displayLabel":"25+ finance employees",
          "searchString":"25 finance employees",
          "description":"This company has 25 or more employees in a finance role",
          "group":"FinanceEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionConsultingEmployees":[
        {
          "value":"#250_plus_consulting",
          "displayLabel":"250+ consultants",
          "searchString":"250 consulting employees",
          "description":"This company has 250 or more employees in a consulting role",
          "group":"ConsultingEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_consulting",
          "displayLabel":"50+ consultants",
          "searchString":"50 consulting employees",
          "description":"This company has 50 or more employees in a consulting role",
          "group":"ConsultingEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_consulting",
          "displayLabel":"100+ consultants",
          "searchString":"100 consulting employees",
          "description":"This company has 100 or more employees in a consulting role",
          "group":"ConsultingEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_consulting",
          "displayLabel":"25+ consultants",
          "searchString":"25 consulting employees",
          "description":"This company has 25 or more employees in a consulting role",
          "group":"ConsultingEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_consulting",
          "displayLabel":"2+ consultants",
          "searchString":"2 consulting employees",
          "description":"This company has 2 or more employees in a consulting role",
          "group":"ConsultingEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_consulting",
          "displayLabel":"500+ consultants",
          "searchString":"500 consulting employees",
          "description":"This company has 500 or more employees in a consulting role",
          "group":"ConsultingEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_consulting",
          "displayLabel":"10+ consultants",
          "searchString":"10 consulting employees",
          "description":"This company has 10 or more employees in a consulting role",
          "group":"ConsultingEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_consulting",
          "displayLabel":"5+ consultants",
          "searchString":"5 consulting employees",
          "description":"This company has 5 or more employees in a consulting role",
          "group":"ConsultingEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_consulting",
          "displayLabel":"1000+ consultants",
          "searchString":"1000 consulting employees",
          "description":"This company has 1000 or more employees in a consulting role",
          "group":"ConsultingEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionMarketingEmployees":[
        {
          "value":"#10_plus_marketing",
          "displayLabel":"10+ marketing employees",
          "searchString":"10 marketing employees",
          "description":"This company has 10 or more employees in a marketing role",
          "group":"MarketingEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_marketing",
          "displayLabel":"500+ marketing employees",
          "searchString":"500 marketing employees",
          "description":"This company has 500 or more employees in a marketing role",
          "group":"MarketingEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_marketing",
          "displayLabel":"250+ marketing employees",
          "searchString":"250 marketing employees",
          "description":"This company has 250 or more employees in a marketing role",
          "group":"MarketingEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_marketing",
          "displayLabel":"1000+ marketing employees",
          "searchString":"1000 marketing employees",
          "description":"This company has 1000 or more employees in a marketing role",
          "group":"MarketingEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_marketing",
          "displayLabel":"5+ marketing employees",
          "searchString":"5 marketing employees",
          "description":"This company has 5 or more employees in a marketing role",
          "group":"MarketingEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_marketing",
          "displayLabel":"2+ marketing employees",
          "searchString":"2 marketing employees",
          "description":"This company has 2 or more employees in a marketing role",
          "group":"MarketingEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_marketing",
          "displayLabel":"25+ marketing employees",
          "searchString":"25 marketing employees",
          "description":"This company has 25 or more employees in a marketing role",
          "group":"MarketingEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_marketing",
          "displayLabel":"100+ marketing employees",
          "searchString":"100 marketing employees",
          "description":"This company has 100 or more employees in a marketing role",
          "group":"MarketingEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_marketing",
          "displayLabel":"50+ marketing employees",
          "searchString":"50 marketing employees",
          "description":"This company has 50 or more employees in a marketing role",
          "group":"MarketingEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionITEmployees":[
        {
          "value":"#500_plus_it",
          "displayLabel":"500+ IT employees",
          "searchString":"500 information technology employees",
          "description":"This company has 500 or more employees in an IT role",
          "group":"ItEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_it",
          "displayLabel":"2+ IT employees",
          "searchString":"2 information technology employees",
          "description":"This company has 2 or more employees in an IT role",
          "group":"ItEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_it",
          "displayLabel":"5+ IT employees",
          "searchString":"5 information technology employees",
          "description":"This company has 5 or more employees in an IT role",
          "group":"ItEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_it",
          "displayLabel":"10+ IT employees",
          "searchString":"10 information technology employees",
          "description":"This company has 10 or more employees in an IT role",
          "group":"ItEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_it",
          "displayLabel":"250+ IT employees",
          "searchString":"250 information technology employees",
          "description":"This company has 250 or more employees in an IT role",
          "group":"ItEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_it",
          "displayLabel":"25+ IT employees",
          "searchString":"25 information technology employees",
          "description":"This company has 25 or more employees in an IT role",
          "group":"ItEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_it",
          "displayLabel":"1000+ IT employees",
          "searchString":"1000 information technology employees",
          "description":"This company has 1000 or more employees in an IT role",
          "group":"ItEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_it",
          "displayLabel":"50+ IT employees",
          "searchString":"50 information technology employees",
          "description":"This company has 50 or more employees in an IT role",
          "group":"ItEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_it",
          "displayLabel":"100+ IT employees",
          "searchString":"100 information technology employees",
          "description":"This company has 100 or more employees in an IT role",
          "group":"ItEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionHREmployees":[
        {
          "value":"#500_plus_hr",
          "displayLabel":"500+ human resource employees",
          "searchString":"500 human resource employees",
          "description":"This company has 500 or more employees in an HR role",
          "group":"HrEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_hr",
          "displayLabel":"25+ human resource employees",
          "searchString":"25 human resource employees",
          "description":"This company has 25 or more employees in an HR role",
          "group":"HrEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_hr",
          "displayLabel":"100+ human resource employees",
          "searchString":"100 human resource employees",
          "description":"This company has 100 or more employees in an HR role",
          "group":"HrEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_hr",
          "displayLabel":"10+ human resource employees",
          "searchString":"10 human resource employees",
          "description":"This company has 10 or more employees in an HR role",
          "group":"HrEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_hr",
          "displayLabel":"5+ human resource employees",
          "searchString":"5 human resource employees",
          "description":"This company has 5 or more employees in an HR role",
          "group":"HrEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_hr",
          "displayLabel":"2+ human resource employees",
          "searchString":"2 human resource employees",
          "description":"This company has 2 or more employees in an HR role",
          "group":"HrEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_hr",
          "displayLabel":"250+ human resource employees",
          "searchString":"250 human resource employees",
          "description":"This company has 250 or more employees in an HR role",
          "group":"HrEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_hr",
          "displayLabel":"1000+ human resource employees",
          "searchString":"1000 human resource employees",
          "description":"This company has 1000 or more employees in an HR role",
          "group":"HrEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_hr",
          "displayLabel":"50+ human resource employees",
          "searchString":"50 human resource employees",
          "description":"This company has 50 or more employees in an HR role",
          "group":"HrEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionEngineeringEmployees":[
        {
          "value":"#2_plus_engineering_and_tech",
          "displayLabel":"2+ engineering employees",
          "searchString":"2 engineering employees",
          "description":"This company has 2 or more employees in an engineering role",
          "group":"EngineeringEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_engineering_and_tech",
          "displayLabel":"500+ engineering employees",
          "searchString":"500 engineering employees",
          "description":"This company has 500 or more employees in an engineering role",
          "group":"EngineeringEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_engineering_and_tech",
          "displayLabel":"50+ engineering employees",
          "searchString":"50 engineering employees",
          "description":"This company has 50 or more employees in an engineering role",
          "group":"EngineeringEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_engineering_and_tech",
          "displayLabel":"1000+ engineering employees",
          "searchString":"1000 engineering employees",
          "description":"This company has 1000 or more employees in an engineering role",
          "group":"EngineeringEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_engineering_and_tech",
          "displayLabel":"250+ engineering employees",
          "searchString":"250 engineering employees",
          "description":"This company has 250 or more employees in an engineering role",
          "group":"EngineeringEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_engineering_and_tech",
          "displayLabel":"100+ engineering employees",
          "searchString":"100 engineering employees",
          "description":"This company has 100 or more employees in an engineering role",
          "group":"EngineeringEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_engineering_and_tech",
          "displayLabel":"5+ engineering employees",
          "searchString":"5 engineering employees",
          "description":"This company has 5 or more employees in an engineering role",
          "group":"EngineeringEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_engineering_and_tech",
          "displayLabel":"25+ engineering employees",
          "searchString":"25 engineering employees",
          "description":"This company has 25 or more employees in an engineering role",
          "group":"EngineeringEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_engineering_and_tech",
          "displayLabel":"10+ engineering employees",
          "searchString":"10 engineering employees",
          "description":"This company has 10 or more employees in an engineering role",
          "group":"EngineeringEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionSoftwareEmployees":[
        {
          "value":"#25_plus_software_engineering",
          "displayLabel":"25+ software engineers",
          "searchString":"25 software employees",
          "description":"This company has 25 or more employees in a software role",
          "group":"SoftwareEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_software_engineering",
          "displayLabel":"50+ software engineers",
          "searchString":"50 software employees",
          "description":"This company has 50 or more employees in a software role",
          "group":"SoftwareEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_software_engineering",
          "displayLabel":"100+ software engineers",
          "searchString":"100 software employees",
          "description":"This company has 100 or more employees in a software role",
          "group":"SoftwareEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_software_engineering",
          "displayLabel":"5+ software engineers",
          "searchString":"5 software employees",
          "description":"This company has 5 or more employees in a software role",
          "group":"SoftwareEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_software_engineering",
          "displayLabel":"2+ software engineers",
          "searchString":"2 software employees",
          "description":"This company has 2 or more employees in a software role",
          "group":"SoftwareEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_software_engineering",
          "displayLabel":"1000+ software engineers",
          "searchString":"1000 software employees",
          "description":"This company has 1000 or more employees in a software role",
          "group":"SoftwareEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_software_engineering",
          "displayLabel":"250+ software engineers",
          "searchString":"250 software employees",
          "description":"This company has 250 or more employees in a software role",
          "group":"SoftwareEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_software_engineering",
          "displayLabel":"10+ software engineers",
          "searchString":"10 software employees",
          "description":"This company has 10 or more employees in a software role",
          "group":"SoftwareEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#500_plus_software_engineering",
          "displayLabel":"500+ software engineers",
          "searchString":"500 software employees",
          "description":"This company has 500 or more employees in a software role",
          "group":"SoftwareEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ],
      "JobFunctionNursingEmployees":[
        {
          "value":"#500_plus_nurses",
          "displayLabel":"500+ nurses",
          "searchString":"500 nursing employees",
          "description":"This company has 500 or more employees in a nursing role",
          "group":"NursingEmployees",
          "priority":"500",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#5_plus_nurses",
          "displayLabel":"5+ nurses",
          "searchString":"5 nursing employees",
          "description":"This company has 5 or more employees in a nursing role",
          "group":"NursingEmployees",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#250_plus_nurses",
          "displayLabel":"250+ nurses",
          "searchString":"250 nursing employees",
          "description":"This company has 250 or more employees in a nursing role",
          "group":"NursingEmployees",
          "priority":"250",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#50_plus_nurses",
          "displayLabel":"50+ nurses",
          "searchString":"50 nursing employees",
          "description":"This company has 50 or more employees in a nursing role",
          "group":"NursingEmployees",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#10_plus_nurses",
          "displayLabel":"10+ nurses",
          "searchString":"10 nursing employees",
          "description":"This company has 10 or more employees in a nursing role",
          "group":"NursingEmployees",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#1000_plus_nurses",
          "displayLabel":"1000+ nurses",
          "searchString":"1000 nursing employees",
          "description":"This company has 1000 or more employees in a nursing role",
          "group":"NursingEmployees",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#2_plus_nurses",
          "displayLabel":"2+ nurses",
          "searchString":"2 nursing employees",
          "description":"This company has 2 or more employees in a nursing role",
          "group":"NursingEmployees",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#100_plus_nurses",
          "displayLabel":"100+ nurses",
          "searchString":"100 nursing employees",
          "description":"This company has 100 or more employees in a nursing role",
          "group":"NursingEmployees",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        },
        {
          "value":"#25_plus_nurses",
          "displayLabel":"25+ nurses",
          "searchString":"25 nursing employees",
          "description":"This company has 25 or more employees in a nursing role",
          "group":"NursingEmployees",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"jobFunction"
        }
      ]
    }
  },
  {
    "parent":"countryLocation",
    "groups":{
      "CountryLocations":[
        {
          "value":"#asia",
          "displayLabel":"Has locations in Asia",
          "searchString":"asia country countries",
          "description":"This company has locations in Asia",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#spain",
          "displayLabel":"Has locations in Spain",
          "searchString":"spain country countries",
          "description":"This company has locations in Spain",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#eu",
          "displayLabel":"Has locations in the EU",
          "searchString":"european union country countries",
          "description":"This company has locations in countries in the European Union",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#netherland",
          "displayLabel":"Has locations in the Netherlands",
          "searchString":"netherlands country countries",
          "description":"This company has locations in Netherlands",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#singapore",
          "displayLabel":"Has locations in Singapore",
          "searchString":"singapore country countries",
          "description":"This company has locations in Singapore",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#southamerica",
          "displayLabel":"Has locations in South America",
          "searchString":"south america country countries",
          "description":"This company has locations in the South America",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#australia",
          "displayLabel":"Has locations in Australia",
          "searchString":"australia country countries",
          "description":"This company has locations in Australia",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#middleeast",
          "displayLabel":"Has locations in the Middle East",
          "searchString":"middle east country countries",
          "description":"This company has locations in the Middle East",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#northamerica",
          "displayLabel":"Has locations in North America",
          "searchString":"north america country countries",
          "description":"This company has locations in North America",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#southafrica",
          "displayLabel":"Has locations in South Africa",
          "searchString":"south Africa country countries",
          "description":"This company has locations in the South Africa",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#germany",
          "displayLabel":"Has locations in Germany",
          "searchString":"germany country countries",
          "description":"This company has locations in Germany",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#europe",
          "displayLabel":"Has locations in Europe",
          "searchString":"europe country countries",
          "description":"This company has locations in Europe",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#switzerland",
          "displayLabel":"Has locations in Switzerland",
          "searchString":"switzerland country countries",
          "description":"This company has locations in Switzerland",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#oceania",
          "displayLabel":"Has locations Oceania",
          "searchString":"oceania country countries",
          "description":"This company has locations in Oceania",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#africa",
          "displayLabel":"Has locations in Africa",
          "searchString":"africa country countries",
          "description":"This company has locations in Africa",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#unitedkingdom",
          "displayLabel":"Has locations in United Kingdom",
          "searchString":"united kingdom country countries",
          "description":"This company has locations in the United Kingdom",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#ireland",
          "displayLabel":"Has locations in Ireland",
          "searchString":"ireland country countries",
          "description":"This company has locations in Ireland",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#italy",
          "displayLabel":"Has locations in Italy",
          "searchString":"italy country countries",
          "description":"This company has locations in Italy",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#france",
          "displayLabel":"Has locations in France",
          "searchString":"france country countries",
          "description":"This company has locations in France",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#mexico",
          "displayLabel":"Has locations in Mexico",
          "searchString":"mexico country countries",
          "description":"This company has locations in Mexico",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#india",
          "displayLabel":"Has locations in India",
          "searchString":"india country countries",
          "description":"This company has locations in India",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#sweden",
          "displayLabel":"Has locations in Sweden",
          "searchString":"sweden country countries",
          "description":"This company has locations in Sweden",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#brazil",
          "displayLabel":"Has locations in Brazil",
          "searchString":"brazil country countries",
          "description":"This company has locations in Brazil",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#asiapacific",
          "displayLabel":"Has locations in Asia-Pacific",
          "searchString":"asia pacific country countries asia-pacific",
          "description":"This company has locations in Asia Pacific",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#unitedarabemirates",
          "displayLabel":"Has locations in United Arab Emirates",
          "searchString":"united arab emirates country countries",
          "description":"This company has locations in the United Arab Emirates",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#canada",
          "displayLabel":"Has locations in Canada",
          "searchString":"canada country countries",
          "description":"This company has locations in Canada",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#china",
          "displayLabel":"Has locations in China",
          "searchString":"china country countries",
          "description":"This company has locations in China",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#belgium",
          "displayLabel":"Has locations in Belgium",
          "searchString":"belgium country countries",
          "description":"This company has locations in Belgium",
          "group":"CountryLocations",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        }
      ],
      "NumberOfLocations":[
        {
          "value":"#10_plus_locations",
          "displayLabel":"10+ locations",
          "searchString":"10 locations",
          "description":"This company has 10 or more locations",
          "group":"NumberOfLocations",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#100_plus_locations",
          "displayLabel":"100+ locations",
          "searchString":"100 locations",
          "description":"This company has 100 or more locations",
          "group":"NumberOfLocations",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#50_plus_locations",
          "displayLabel":"50+ locations",
          "searchString":"50 locations",
          "description":"This company has 50 or more locations",
          "group":"NumberOfLocations",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#25_plus_locations",
          "displayLabel":"25+ locations",
          "searchString":"25 locations",
          "description":"This company has 25 or more locations",
          "group":"NumberOfLocations",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#2_plus_locations",
          "displayLabel":"2+ locations",
          "searchString":"2 locations",
          "description":"This company has 2 or more locations",
          "group":"NumberOfLocations",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        },
        {
          "value":"#5_plus_locations",
          "displayLabel":"5+ locations",
          "searchString":"5 locations",
          "description":"This company has 5 or more locations",
          "group":"NumberOfLocations",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"countryLocation"
        }
      ]
    }
  },
  {
    "parent":"Ranking",
    "groups":{
      "Ranking":[
        {
          "value":"#global2000.2017",
          "displayLabel":"2017 Global 2000",
          "searchString":"global 2000",
          "description":"This company is on the 2017 Global 2000 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#global2000.2018",
          "displayLabel":"2018 Global 2000",
          "searchString":"global 2000",
          "description":"This company is on the 2018 Global 2000 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_small_workplaces50.2016",
          "displayLabel":"2016 Best Small Workplaces",
          "searchString":"best small workplaces",
          "description":"This company is on the 2016 Best Small Workplaces list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_small_workplaces50.2017",
          "displayLabel":"2017 Best Small Workplaces",
          "searchString":"best small workplaces",
          "description":"This company is on the 2017 Best Small Workplaces list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_small_workplaces50.2018",
          "displayLabel":"2018 Best Small Workplaces",
          "searchString":"best small workplaces",
          "description":"This company is on the 2018 Best Small Workplaces list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#americas_best_midsize_employers.2018",
          "displayLabel":"2018 America's Best Midsize Employers",
          "searchString":"americas best midsize employers",
          "description":"This company is on the 2018 America's Best Midsize Employers list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_workplaces_for_millennials100.2018",
          "displayLabel":"2018 Best Workplaces For Millennials",
          "searchString":"best workplaces for millennials",
          "description":"This company is on the 2018 Best Workplaces For Millennials list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#americas_best_midsize_employers.2017",
          "displayLabel":"2017 America's Best Midsize Employers",
          "searchString":"americas best midsize employers",
          "description":"This company is on the 2017 America's Best Midsize Employers list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_workplaces_for_millennials100.2017",
          "displayLabel":"2017 Best Workplaces For Millennials",
          "searchString":"best workplaces for millennials",
          "description":"This company is on the 2017 Best Workplaces For Millennials list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_workplaces_for_millennials100.2016",
          "displayLabel":"2016 Best Workplaces For Millennials",
          "searchString":"best workplaces for millennials",
          "description":"This company is on the 2016 Best Workplaces For Millennials list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#canada_profit500.2017",
          "displayLabel":"2017 Canada's Fastest Growing Companies",
          "searchString":"canadas fastest growing companies",
          "description":"This company is on the 2017 Canada's Fastest Growing Companies list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#techfast500.2017",
          "displayLabel":"Technology Fast 500 2017",
          "searchString":"technology fast 500",
          "description":"This company is on the 2017 Deloitte Technology Fast 500 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#techfast500.2018",
          "displayLabel":"2018 Technology Fast 500",
          "searchString":"technology fast 500",
          "description":"This company is on the 2018 Deloitte Technology Fast 500 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#unicorn_list.2016",
          "displayLabel":"2016 Unicorn List",
          "searchString":"unicorn list",
          "description":"This company is on the 2016 Unicorn list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_workplaces_for_flexibility50.2016",
          "displayLabel":"2016 Best Workplaces For Flexibility",
          "searchString":"best workplaces for flexibility",
          "description":"This company is on the 2016 Best Workplaces For Flexibility list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#canadas_best_employers.2018",
          "displayLabel":"2018 Canada's Best Employers",
          "searchString":"canadas best employers",
          "description":"This company is on the 2018 Canada's Best Employers list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#worlds_most_admired.2018",
          "displayLabel":"2018 World's Most Admired Companies",
          "searchString":"worlds most admired companies",
          "description":"This company is on the 2018 World's Most Admired Companies list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#worlds_most_admired.2017",
          "displayLabel":"2017 World's Most Admired Companies",
          "searchString":"worlds most admired companies",
          "description":"This company is on the 2017 World's Most Admired Companies list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#worlds_most_innovative.2016",
          "displayLabel":"2016 World's Most Innovative Companies",
          "searchString":"worlds most innovative",
          "description":"This company is on the 2016 World's Most Innovative Companies list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#worlds_most_innovative.2017",
          "displayLabel":"2017 World's Most Innovative Companies",
          "searchString":"worlds most innovative",
          "description":"This company is on the 2017 World's Most Innovative Companies list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#worlds_most_innovative.2018",
          "displayLabel":"2018 World's Most Innovative Companies",
          "searchString":"worlds most innovative",
          "description":"This company is on the 2018 World's Most Innovative Companies list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_large_workplaces_for_women.2018",
          "displayLabel":"2018 Best Large Workplaces For Women",
          "searchString":"best large workplaces for women",
          "description":"This company is on the 2018 Best Large Workplaces For Women list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#diversity50.2016",
          "displayLabel":"2016 Best Workplaces For Diversity",
          "searchString":"best workplaces for diversity",
          "description":"This company is on the 2016 Best Workplaces For Diversity list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#most_promising.2015",
          "displayLabel":"2015 America's Most Promising",
          "searchString":"americas most promising",
          "description":"This company is on the 2015 America's Most Promising list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_workplaces_for_college_grads50.2016",
          "displayLabel":"2016 Best Workplaces For College Grads",
          "searchString":"best workplaces for college grads",
          "description":"This company is on the 2016 Best Workplaces For College Grads list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#russell3000",
          "displayLabel":"Russell 3000",
          "searchString":"russell 3000",
          "description":"This company is on the Russell 3000 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#franchisetop500",
          "displayLabel":"Franchise Top 500",
          "searchString":"franchise top 500",
          "description":"This company is on Entrepreneur's Franchise 500 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#b2c",
          "displayLabel":"B2C",
          "searchString":"b2c",
          "description":"This is a company that does business-to-consumer selling",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#asia_fab50.2016",
          "displayLabel":"2016 Asia Fab 50",
          "searchString":"asia fab",
          "description":"This company is on the 2016 Asia Fab 50 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#asia_fab50.2018",
          "displayLabel":"2018 Asia Fab 50",
          "searchString":"asia fab",
          "description":"This company is on the 2018 Asia Fab 50 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#asia_fab50.2017",
          "displayLabel":"2017 Asia Fab 50",
          "searchString":"asia fab",
          "description":"This company is on the 2017 Asia Fab 50 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_companies_to_work_for100.2017",
          "displayLabel":"2017 Best Companies To Work For",
          "searchString":"best companies to work for",
          "description":"This company is on the 2017 Best Companies To Work For list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_workplaces_for_women100.2016",
          "displayLabel":"2016 Best Workplaces For Women",
          "searchString":"best workplaces for women",
          "description":"This company is on the 2016 Best Workplaces For Women list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_workplaces_for_women100.2017",
          "displayLabel":"2017 Best Workplaces For Women",
          "searchString":"best workplaces for women",
          "description":"This company is on the 2017 Best Workplaces For Women list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#inc5000.2016",
          "displayLabel":"2016 Inc 5000",
          "searchString":"inc 5000",
          "description":"This company is on the 2016 Inc 5000 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#inc5000.2018",
          "displayLabel":"2018 Inc 5000",
          "searchString":"inc 5000",
          "description":"This company is on the 2018 Inc 5000 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#inc5000.2017",
          "displayLabel":"2017 Inc 5000",
          "searchString":"inc 5000",
          "description":"This company is on the 2017 Inc 5000 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#eu_inc5000.2018",
          "displayLabel":"2018 EU Inc 5000",
          "searchString":"eu inc 5000",
          "description":"This company is on the 2018 EU Inc 5000 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#eu_inc5000.2016",
          "displayLabel":"2016 EU Inc 5000",
          "searchString":"eu inc 5000",
          "description":"This company is on the 2016 EU Inc 5000 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#eu_inc5000.2017",
          "displayLabel":"2017 EU Inc 5000",
          "searchString":"eu inc 5000",
          "description":"This company is on the 2017 EU Inc 5000 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#cloud100.2018",
          "displayLabel":"2018 Cloud 100",
          "searchString":"cloud 100",
          "description":"This company is on the 2018 Cloud 100 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#cloud100.2017",
          "displayLabel":"2017 Cloud 100",
          "searchString":"cloud 100",
          "description":"This company is on the 2017 Cloud 100 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#crn500.2017",
          "displayLabel":"2017 Solution Provider 500",
          "searchString":"solution provider",
          "description":"This company is on the 2017 Solution Provider 500 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_medium_workplaces100.2018",
          "displayLabel":"2018 Best Medium Workplaces",
          "searchString":"best medium workplaces",
          "description":"This company is on the 2018 Best Medium Workplaces list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_medium_workplaces100.2017",
          "displayLabel":"2017 Best Medium Workplaces",
          "searchString":"best medium workplaces",
          "description":"This company is on the 2017 Best Medium Workplaces list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_workplaces_for_parents50.2016",
          "displayLabel":"2016 Best Workplaces For Parents",
          "searchString":"best workplaces for parents",
          "description":"This company is on the 2016 Best Workplaces For Parents list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_medium_workplaces100.2016",
          "displayLabel":"2016 Best Medium Workplaces",
          "searchString":"best medium workplaces",
          "description":"This company is on the 2016 Best Medium Workplaces list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#small_giants.2018",
          "displayLabel":"2018 Small Giants",
          "searchString":"small giants",
          "description":"This company is on the 2018 Small Giants list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#small_giants.2017",
          "displayLabel":"2017 Small Giants",
          "searchString":"small giants",
          "description":"This company is on the 2017 \"Small Giants\" list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#inner_city100.2018",
          "displayLabel":"2018 Inner City 100",
          "searchString":"inner city 100",
          "description":"This company is on the 2018 Inner City 100 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#inner_city100.2017",
          "displayLabel":"2017 Inner City 100",
          "searchString":"inner city 100",
          "description":"This company is on the 2017 Inner City 100 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#diversity100.2017",
          "displayLabel":"2017 Diversity 100",
          "searchString":"diversity 100",
          "description":"This company is on the 2017 Diversity 100 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#most_valuable_brands.2017",
          "displayLabel":"2017 World's Most Valuable Brands",
          "searchString":"worlds most valuable brands",
          "description":"This company is on the 2017 World's Most Valuable Brands list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#most_valuable_brands.2018",
          "displayLabel":"2018 World's Most Valuable Brands",
          "searchString":"worlds most valuable brands",
          "description":"This company is on the 2018 World's Most Valuable Brands list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#americas_best_employers.2017",
          "displayLabel":"2017 America's Best Employers",
          "searchString":"americas best employers",
          "description":"This company is on the 2017 America's Best Employers list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#americas_best_employers.2018",
          "displayLabel":"2018 America's Best Employers",
          "searchString":"americas best employers",
          "description":"This company is on the 2018 America's Best Employers list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#inner_city100.2016",
          "displayLabel":"2016 Inner City 100",
          "searchString":"inner city 100",
          "description":"This company is on the 2016 Inner City 100 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#change_the_world50.2017",
          "displayLabel":"2017 Change The World 50",
          "searchString":"change the world 50",
          "description":"This company is on the 2017 Change The World 50 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#best_companies_to_work_for.2018",
          "displayLabel":"2018 Best Companies To Work For",
          "searchString":"best companies to work for",
          "description":"This company is on the 2018 Best Companies To Work For list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#techfast500",
          "displayLabel":"Technology Fast 500 2016",
          "searchString":"technology fast 500",
          "description":"This company is on the 2016 Deloitte Technology Fast 500 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#worlds_most_innovative_growth.2017",
          "displayLabel":"2017 World's Most Innovative Growth Companies",
          "searchString":"worlds most innovative growth companies",
          "description":"This company is on the 2017 World's Most Innovative Growth list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        },
        {
          "value":"#change_the_world50.2018",
          "displayLabel":"2018 Change The World 50",
          "searchString":"change the world 50",
          "description":"This company is on the 2018 Change The World 50 list",
          "group":"Ranking",
          "isCategorized":"false",
          "parentCategory":"ranking"
        }
      ]
    }
  },
  {
    "parent":"Banking",
    "groups":{
      "BankingAssets":[
        {
          "value":"#bank.assets.100mplu",
          "displayLabel":"Bank with $100+ million assets held",
          "searchString":"100 million assets fdic bank",
          "description":"This company is an FDIC insured bank with $100 million or more dollars in assets held",
          "group":"BankingAssets",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.assets.100bplu",
          "displayLabel":"Bank with $100+ billion assets held",
          "searchString":"100 billion assets fdic bank",
          "description":"This company is an FDIC insured bank with $100 billion or more dollars in assets held",
          "group":"BankingAssets",
          "priority":"10000",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.assets.1tplu",
          "displayLabel":"Bank with $1+ trillion assets held",
          "searchString":"1 trillion assets fdic bank",
          "description":"This company is an FDIC insured bank with $1 trillion or more dollars in assets held",
          "group":"BankingAssets",
          "priority":"100000",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.assets.1mplu",
          "displayLabel":"Bank with $1+ million assets held",
          "searchString":"1 million assets fdic bank",
          "description":"This company is an FDIC insured bank with $1 million or more dollars in assets held",
          "group":"BankingAssets",
          "priority":"1",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.assets.1bplu",
          "displayLabel":"Bank with $1+ billion assets held",
          "searchString":"1 billion assets fdic bank",
          "description":"This company is an FDIC insured bank with $1 billion or more dollars in assets held",
          "group":"BankingAssets",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.assets.10bplu",
          "displayLabel":"Bank with $10+ billion assets held",
          "searchString":"10 billion assets fdic bank",
          "description":"This company is an FDIC insured bank with $10 billion or more dollars in assets held",
          "group":"BankingAssets",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"banking"
        }
      ],
      "LocationsBanking":[
        {
          "value":"#bank.branches.10plus",
          "displayLabel":"10+ bank branches",
          "searchString":"10 branch locations fdic bank",
          "description":"This company is an FDIC insured bank with 10 or more branch locations",
          "group":"NumberOfBankBranches",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.branches.5plus",
          "displayLabel":"5+ bank branches",
          "searchString":"5 branch locations fdic bank",
          "description":"This company is an FDIC insured bank with 5 or more branch locations",
          "group":"NumberOfBankBranches",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.branches.50plus",
          "displayLabel":"50+ bank branches",
          "searchString":"50 branch locations fdic bank",
          "description":"This company is an FDIC insured bank with 50 or more branch locations",
          "group":"NumberOfBankBranches",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.branches.100plus",
          "displayLabel":"100+ bank branches",
          "searchString":"100 branch locations fdic bank",
          "description":"This company is an FDIC insured bank with 100 or more branch locations",
          "group":"NumberOfBankBranches",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.branches.1kplus",
          "displayLabel":"1000+ bank branches",
          "searchString":"1000 branch locations fdic bank",
          "description":"This company is an FDIC insured bank with 1000 or more branch locations",
          "group":"NumberOfBankBranches",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#bank.branches.2plus",
          "displayLabel":"2+ bank branches",
          "searchString":"2 branch locations fdic bank",
          "description":"This company is an FDIC insured bank with 2 or more branch locations",
          "group":"NumberOfBankBranches",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"banking"
        }
      ],
      "LocationsCreditUnions":[
        {
          "value":"#creditunion.branches.2plus",
          "displayLabel":"2+ credit union branches",
          "searchString":"2 branch locations credit union",
          "description":"This company is a credit union with 2 or more branch locations",
          "group":"NumberOfCreditUnions",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#creditunion.branches.100plus",
          "displayLabel":"100+ credit union branches",
          "searchString":"100 branch locations credit union",
          "description":"This company is a credit union with 100 or more branch locations",
          "group":"NumberOfCreditUnions",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#creditunion.branches.50plus",
          "displayLabel":"50+ credit union branches",
          "searchString":"50 branch locations credit union",
          "description":"This company is a credit union with 50 or more branch locations",
          "group":"NumberOfCreditUnions",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#creditunion.branches.5plus",
          "displayLabel":"5+ credit union branches",
          "searchString":"5 branch locations credit union",
          "description":"This company is a credit union with 5 or more branch locations",
          "group":"NumberOfCreditUnions",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#creditunion.branches.10plus",
          "displayLabel":"10+ credit union branches",
          "searchString":"10 branch locations credit union",
          "description":"This company is a credit union with 10 or more branch locations",
          "group":"NumberOfCreditUnions",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"banking"
        }
      ],
      "BankType":[
        {
          "value":"#bank",
          "displayLabel":"FDIC Insured Bank",
          "searchString":"fdic bank",
          "description":"This company is an FDIC insured bank",
          "group":"BankType",
          "isCategorized":"false",
          "parentCategory":"banking"
        },
        {
          "value":"#creditunion",
          "displayLabel":"Credit Union",
          "searchString":"credit union",
          "description":"This company is a credit union",
          "group":"BankType",
          "isCategorized":"false",
          "parentCategory":"banking"
        }
      ]
    }
  },
  {
    "parent":"Other",
    "groups":{
      "Other":[
        {
          "value":"#nursinghome.beds.5plus",
          "displayLabel":"5+ nursing home beds",
          "searchString":"5 nursing home beds",
          "description":"This company is a Nursing Home with 5 or more beds",
          "group":"Other",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking",
          "displayLabel":"Trucking Operator",
          "searchString":"trucking",
          "description":"This company owns trucks according to the USDOT",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#hospital.ownership.nonprofit",
          "displayLabel":"Medicare registered nonprofit hospital",
          "searchString":"medicare nonprofit hospital",
          "description":"This company is a nonprofit hospital registered with the medicare program",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#hospital.ownership.government",
          "displayLabel":"Medicare registered government-owned hospital",
          "searchString":"medicare government hospital",
          "description":"This company is a government-owned hospital registered with the medicare program",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#dialysiscenter",
          "displayLabel":"Medicare registered dialysis center",
          "searchString":"medicare dialysis center",
          "description":"This company is a dialysis center registered with the medicare program",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#value_added_reseller",
          "displayLabel":"VAR/Value-added-reseller",
          "searchString":"var reseller other",
          "description":"This company is a Value Added Reseller",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#fiscalyearend.0630",
          "displayLabel":"Fiscal year ends on June 30",
          "searchString":"Fiscal year end June 30",
          "description":"This company's fiscal year ends on June 30th",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#fiscalyearend.0930",
          "displayLabel":"Fiscal year ends on September 30",
          "searchString":"Fiscal year end September 30",
          "description":"This company's fiscal year ends on September 30th",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#hospital.ownership.proprietary",
          "displayLabel":"Medicare registered proprietary hospital",
          "searchString":"medicare proprietary hospital",
          "description":"This company is a proprietary hospital registered with the medicare program",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#nursinghome",
          "displayLabel":"Nursing Home",
          "searchString":"nursing home",
          "description":"This company is a Nursing Home",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#nursinghome.beds.50plus",
          "displayLabel":"50+ nursing home beds",
          "searchString":"50 nursing home beds",
          "description":"This company is a Nursing Home with 50 or more beds",
          "group":"Other",
          "priority":"50",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#call_center",
          "displayLabel":"Has a call center",
          "searchString":"call center",
          "description":"This company has a call center",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#b2b",
          "displayLabel":"B2B",
          "searchString":"b2b",
          "description":"This is a company that does business-to-business selling",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#has_warehouse",
          "displayLabel":"Has a warehouse",
          "searchString":"warehouse other",
          "description":"This company has a warehouse",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#distributor",
          "displayLabel":"Distributor",
          "searchString":"distributor other",
          "description":"This company is a distributor",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#technology",
          "displayLabel":"Technology",
          "searchString":"technology other",
          "description":"This company is in the technology industry",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#nursinghome.beds.10plus",
          "displayLabel":"10+ nursing home beds",
          "searchString":"10 nursing home beds",
          "description":"This company is a Nursing Home with 10 or more beds",
          "group":"Other",
          "priority":"10",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#mobile_app",
          "displayLabel":"Mobile Application",
          "searchString":"mobile application other",
          "description":"This company has a mobile application",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#fiscalyearend.0331",
          "displayLabel":"Fiscal year ends on March 31",
          "searchString":"Fiscal year end March 31",
          "description":"This company's fiscal year ends on March 31st",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#nursinghome.beds.100plus",
          "displayLabel":"100+ nursing home beds",
          "searchString":"100 nursing home beds",
          "description":"This company is a Nursing Home with 100 or more beds",
          "group":"Other",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#hospiceagency",
          "displayLabel":"Medicare registered hospice agency",
          "searchString":"medicare hospice agency",
          "description":"This company is a hospice agency registered with the medicare program",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#international",
          "displayLabel":"International",
          "searchString":"international other",
          "description":"This company has an international presence",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#nursinghome.beds.200plus",
          "displayLabel":"200+ nursing home beds",
          "searchString":"200 nursing home beds",
          "description":"This company is a Nursing Home with 200 or more beds",
          "group":"Other",
          "priority":"200",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#managed_service_provider",
          "displayLabel":"Managed Service Provider",
          "searchString":"managed service provider",
          "description":"This company is a Managed Service Provider",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#fiscalyearend.1231",
          "displayLabel":"Fiscal year ends on December 31",
          "searchString":"Fiscal year end December 31",
          "description":"This company's fiscal year ends on December 31st",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#franchise",
          "displayLabel":"Franchise",
          "searchString":"franchise",
          "description":"This company is a Franchise",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#hospital",
          "displayLabel":"Medicare registered hospital",
          "searchString":"medicare hospital",
          "description":"This company is a hospital registered with the medicare program",
          "group":"Other",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#nursinghome.beds.2plus",
          "displayLabel":"2+ nursing home beds",
          "searchString":"2 nursing home beds",
          "description":"This company is a Nursing Home with 2 or more beds",
          "group":"Other",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#nursinghome.beds.25plus",
          "displayLabel":"25+ nursing home beds",
          "searchString":"25 nursing home beds",
          "description":"This company is a Nursing Home with 25 or more beds",
          "group":"Other",
          "priority":"25",
          "isCategorized":"false",
          "parentCategory":"other"
        }
      ],
      "TruckingTrucks":[
        {
          "value":"#trucking.trucks.2plu",
          "displayLabel":"2+ trucks",
          "searchString":"2 trucks",
          "description":"This company has 2 or more trucks",
          "group":"Trucking",
          "priority":"1",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.trucks.5plu",
          "displayLabel":"5+ trucks",
          "searchString":"5 trucks",
          "description":"This company has 5 or more trucks",
          "group":"Trucking",
          "priority":"2",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.trucks.10plu",
          "displayLabel":"10+ trucks",
          "searchString":"10 trucks",
          "description":"This company has 10 or more trucks",
          "group":"Trucking",
          "priority":"3",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.trucks.25plu",
          "displayLabel":"25+ trucks",
          "searchString":"25 trucks",
          "description":"This company has 25 or more trucks",
          "group":"Trucking",
          "priority":"4",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.trucks.50plu",
          "displayLabel":"50+ trucks",
          "searchString":"50 trucks",
          "description":"This company has 50 or more trucks",
          "group":"Trucking",
          "priority":"5",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.trucks.100plu",
          "displayLabel":"100+ trucks",
          "searchString":"100 trucks",
          "description":"This company has 100 or more trucks",
          "group":"Trucking",
          "priority":"6",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.trucks.250plu",
          "displayLabel":"250+ trucks",
          "searchString":"250 trucks",
          "description":"This company has 250 or more trucks",
          "group":"Trucking",
          "priority":"7",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.trucks.1000plu",
          "displayLabel":"1000+ trucks",
          "searchString":"1000 trucks",
          "description":"This company has 1000 or more trucks",
          "group":"Trucking",
          "priority":"8",
          "isCategorized":"false",
          "parentCategory":"other"
        },


        {
          "value":"#trucking.drivers.2plu",
          "displayLabel":"2+ truck drivers",
          "searchString":"2 truck drivers",
          "description":"This company has 2 or more truck drivers",
          "group":"Trucking",
          "priority":"11",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.drivers.5plu",
          "displayLabel":"5+ truck drivers",
          "searchString":"5 truck drivers",
          "description":"This company has 5 or more truck drivers",
          "group":"Trucking",
          "priority":"12",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.drivers.10plu",
          "displayLabel":"10+ truck drivers",
          "searchString":"10 truck drivers",
          "description":"This company has 10 or more truck drivers",
          "group":"Trucking",
          "priority":"13",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.drivers.25plu",
          "displayLabel":"25+ truck drivers",
          "searchString":"25 truck drivers",
          "description":"This company has 25 or more truck drivers",
          "group":"Trucking",
          "priority":"14",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.drivers.50plu",
          "displayLabel":"50+ truck drivers",
          "searchString":"50 truck drivers",
          "description":"This company has 50 or more truck drivers",
          "group":"Trucking",
          "priority":"15",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.drivers.100plu",
          "displayLabel":"100+ truck drivers",
          "searchString":"100 truck drivers",
          "description":"This company has 100 or more truck drivers",
          "group":"Trucking",
          "priority":"16",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.drivers.250plu",
          "displayLabel":"250+ truck drivers",
          "searchString":"250 truck drivers",
          "description":"This company has 250 or more truck drivers",
          "group":"TruckingDrivers",
          "priority":"17",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.drivers.1000plu",
          "displayLabel":"1000+ truck drivers",
          "searchString":"1000 truck drivers",
          "description":"This company has 1000 or more truck drivers",
          "group":"Trucking",
          "priority":"18",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.intrastate.nonhazmat",
          "displayLabel":"Intrastate Nonhazmat Trucking Operator",
          "searchString":"intrastate nonhazmat trucking",
          "description":"This is a company with an intrastate non-hazmat carrier trucking designation according to the USDOT.",
          "group":"Trucking",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.intrastate.hazmat",
          "displayLabel":"Intrastate Hazmat Trucking Operator",
          "searchString":"intrastate hazmat trucking",
          "description":"This is a company with an intrastate hazmat carrier trucking designation according to the USDOT.",
          "group":"Trucking",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#trucking.interstate",
          "displayLabel":"Interstate Trucking Operator",
          "searchString":"interstate trucking",
          "description":"This is a company with an interstate carrier trucking designation according to the USDOT.",
          "group":"Trucking",
          "isCategorized":"false",
          "parentCategory":"other"
        }
      ],
      "Founded":[
        {
          "value":"(#founded_2017 or #founded_2016 or #founded_2015 or #founded_2014 or #founded_2013 or #founded_2012)",
          "displayLabel":"Founded in the last 5 years",
          "searchString":"Founded in last 5 years",
          "description":"This company was founded in the last 5 years",
          "group":"Founded",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"(#founded_* and not (#founded_2017 or #founded_2016 or #founded_2015 or #founded_2014 or #founded_2013 or #founded_2012 or #founded_2011 or #founded_2010 or #founded_2009 or #founded_2008 or #founded_2007))",
          "displayLabel":"Founded 10+ years ago",
          "searchString":"Founded 10+ years ago",
          "description":"This company was founded more than 10 years ago",
          "group":"Founded",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"(#founded_2017 or #founded_2016 or #founded_2015 or #founded_2014 or #founded_2013 or #founded_2012 or #founded_2011 or #founded_2010 or #founded_2009 or #founded_2008 or #founded_2007)",
          "displayLabel":"Founded in the last 10 years",
          "searchString":"Founded in last 10 years",
          "description":"This company was founded in the last 10 years",
          "group":"Founded",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"(#founded_2017 or #founded_2016 or #founded_2015)",
          "displayLabel":"Founded in the last 2 years",
          "searchString":"Founded in last 2 years",
          "description":"This company was founded in the last 2 years",
          "group":"Founded",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"(#founded_2017 or #founded_2016)",
          "displayLabel":"Founded in the last year",
          "searchString":"Founded in last year",
          "description":"This company was founded in the last year",
          "group":"Founded",
          "isCategorized":"false",
          "parentCategory":"other"
        }
      ],
      "Alexa":[
        {
          "value":"#alexatop100k",
          "displayLabel":"Alexa top 100k",
          "searchString":"alexa top 100000",
          "description":"This company's website is in the top 100k Alexa rankings",
          "group":"Alexa",
          "priority":"100",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#alexatop1000",
          "displayLabel":"Alexa top 1000",
          "searchString":"alexa top 1000",
          "description":"This company's website is in the top 1000 Alexa rankings",
          "group":"Alexa",
          "priority":"10000",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#alexatop10k",
          "displayLabel":"Alexa top 10k",
          "searchString":"alexa top 10000",
          "description":"This company's website is in the top 10k Alexa rankings",
          "group":"Alexa",
          "priority":"1000",
          "isCategorized":"false",
          "parentCategory":"other"
        },
        {
          "value":"#alexatop100",
          "displayLabel":"Alexa top 100",
          "searchString":"alexa top 100",
          "description":"This company's website is in the top 100 Alexa rankings",
          "group":"Alexa",
          "priority":"100000",
          "isCategorized":"false",
          "parentCategory":"other"
        }
      ],
      "LawFirms":[
        {
          "value":"#lawfirm.byrevenue.top100",
          "displayLabel":"Top 100 law firm by revenue",
          "searchString":"top 100 lawfirm by revenue",
          "description":"This company is a law firm in top 100 by revenue",
          "group":"LawFirms",
          "isCategorized":"false",
          "parentCategory":"other"
        }
      ]
    }
  }
]