zoomApiCredsEncryptionPK=ag/23e8Ad4iKzpuf9Lsudg==
zoomApiCredsEncryptionIV=MZbj4033XHoIaGVJg0aIPg==
zoomSessionExpireMinutes=1440
zoomIdExpireMinutes=900
zoomApiAuthUser=https://partnerapi.zoominfo.com/partnerapi/zoom/authn/pro
zoomApiSearch=https://partnerapi.zoominfo.com/partnerapi/
zoomApiCredits=https://partnerapi.zoominfo.com/partnerapi/zoom/credits/dec/
zoomApiView=https://subscriber.zoominfo.com/bizservices/view/contact
zoomIsExportedApi=https://subscriber.zoominfo.com/bizservices/export/isExported/person
zoomUserInfoApi=https://subscriber.zoominfo.com/bizservices/userinfo
zoomLogMaxSize=250
zoomAllUserTokens=https://go.zoominfo.com/anura/userMangment/zoomLoginByZiid
hasEnoughCredits=https://go.zoominfo.com/anura/userData/hasEnoughCredits
purchaseContacts=https://go.zoominfo.com/anura/userData/purchaseContacts
purchaseAccounts=https://go.zoominfo.com/anura/userData/purchaseAccounts
zoomApiCompanyAttribute=https://go.zoominfo.com/anura/company-attributes/get-tree
zoomApiTechAttribute=https://go.zoominfo.com/anura/techAttributes/techAttributesAsTree
zoomFreeExportRoles=FREE_EXPORT
zoomTeamRoles=TEAM
zoomInfoReportFolder=ZoomInfo_Reports
zoomTechAttrRoles=TECH,TEAM
relevantRoles=TECH,TEAM,FREE_EXPORT
LCTriggerSFUsername=LCTriggerZiPro
LCTriggerErorrHandlerCron=0 0 * * * ?
zoomDefaultErrorsEmailAddress=salesforcedev@zoominfo.com
LCTriggerZISessionUpdateCron=0 0 0 * * ?