zoomApiCredsEncryptionPK=ag/23e8Ad4iKzpuf9Lsudg==
zoomApiCredsEncryptionIV=MZbj4033XHoIaGVJg0aIPg==
zoomSessionExpireMinutes=1440
zoomIdExpireMinutes=129600
zoomApiAuthUser=https://partnerapi.zoominfo.com/partnerapi/zoom/authn/pro
zoomApiSearch=https://partnerapi.zoominfo.com/partnerapi/
zoomApiCredits=https://partnerapi.zoominfo.com/partnerapi/zoom/credits/dec/
zoomApiView=https://subscriber.zoominfo.com/bizservices/view/contact
zoomLogMaxSize=250
LCTriggerSFUsername=LCTriggerZiPro
LCTriggerErorrHandlerCron=0 0 * * * ?
zoomDefaultErrorsEmailAddress=salesforcedev@zoominfo.com
LCTriggerZISessionUpdateCron=0 0 0 * * ?